#ChipScope Core Inserter Project File Version 3.0
#Mon Nov 21 15:31:38 CST 2016
Project.device.designInputFile=F\:\\theproject\\14_ethernet_test\\ethernet_test_cs.ngc
Project.device.designOutputFile=F\:\\theproject\\14_ethernet_test\\ethernet_test_cs.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=F\:\\theproject\\14_ethernet_test\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=tx*
Project.filter<10>=*lvalReg*
Project.filter<11>=*dat*
Project.filter<12>=*outDat*
Project.filter<13>=*pClk*
Project.filter<14>=*l_count2*
Project.filter<15>=*d_count_reg*
Project.filter<16>=*l_count_reg*
Project.filter<17>=*f_count_reg*
Project.filter<18>=*empty*
Project.filter<1>=tx
Project.filter<2>=
Project.filter<3>=*tx*
Project.filter<4>=*val_data*
Project.filter<5>=*test_data*
Project.filter<6>=*read_en*
Project.filter<7>=*camera_pause*
Project.filter<8>=*dvalReg*
Project.filter<9>=*fvalReg*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=cameraout pClk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=cameraout tx<0>
Project.unit<0>.dataChannel<10>=cameraout test_data<0>
Project.unit<0>.dataChannel<11>=cameraout test_data<1>
Project.unit<0>.dataChannel<12>=cameraout test_data<2>
Project.unit<0>.dataChannel<13>=cameraout test_data<3>
Project.unit<0>.dataChannel<14>=cameraout test_data<4>
Project.unit<0>.dataChannel<15>=cameraout test_data<5>
Project.unit<0>.dataChannel<16>=cameraout test_data<6>
Project.unit<0>.dataChannel<17>=cameraout test_data<7>
Project.unit<0>.dataChannel<18>=cameraout val_data<0>
Project.unit<0>.dataChannel<19>=cameraout val_data<1>
Project.unit<0>.dataChannel<1>=cameraout tx<1>
Project.unit<0>.dataChannel<20>=cameraout val_data<2>
Project.unit<0>.dataChannel<21>=cameraout val_data<3>
Project.unit<0>.dataChannel<22>=cameraout val_data<4>
Project.unit<0>.dataChannel<23>=cameraout val_data<5>
Project.unit<0>.dataChannel<24>=cameraout val_data<6>
Project.unit<0>.dataChannel<25>=cameraout val_data<7>
Project.unit<0>.dataChannel<26>=cameraout val_data<8>
Project.unit<0>.dataChannel<27>=cameraout val_data<9>
Project.unit<0>.dataChannel<28>=cameraout val_data<10>
Project.unit<0>.dataChannel<2>=cameraout tx<2>
Project.unit<0>.dataChannel<3>=cameraout tx<3>
Project.unit<0>.dataChannel<4>=cameraout tx<4>
Project.unit<0>.dataChannel<5>=cameraout tx<5>
Project.unit<0>.dataChannel<6>=cameraout lvalReg
Project.unit<0>.dataChannel<7>=cameraout fvalReg
Project.unit<0>.dataChannel<8>=cameraout camera_pause
Project.unit<0>.dataChannel<9>=cameraout read_en
Project.unit<0>.dataDepth=8192
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=29
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=cameraout tx<7>
Project.unit<0>.triggerChannel<0><1>=cameraout tx<8>
Project.unit<0>.triggerChannel<0><2>=cameraout tx<9>
Project.unit<0>.triggerChannel<0><3>=cameraout tx<12>
Project.unit<0>.triggerChannel<0><4>=cameraout tx<13>
Project.unit<0>.triggerChannel<0><5>=cameraout tx<14>
Project.unit<0>.triggerChannel<1><0>=cameraout lvalReg
Project.unit<0>.triggerChannel<2><0>=cameraout fvalReg
Project.unit<0>.triggerChannel<3><0>=cameraout camera_pause
Project.unit<0>.triggerChannel<4><0>=cameraout read_en
Project.unit<0>.triggerChannel<5><0>=cameraout test_data<0>
Project.unit<0>.triggerChannel<5><1>=cameraout test_data<1>
Project.unit<0>.triggerChannel<5><2>=cameraout test_data<2>
Project.unit<0>.triggerChannel<5><3>=cameraout test_data<3>
Project.unit<0>.triggerChannel<5><4>=cameraout test_data<4>
Project.unit<0>.triggerChannel<5><5>=cameraout test_data<5>
Project.unit<0>.triggerChannel<5><6>=cameraout test_data<6>
Project.unit<0>.triggerChannel<5><7>=cameraout test_data<7>
Project.unit<0>.triggerChannel<6><0>=cameraout val_data<0>
Project.unit<0>.triggerChannel<6><10>=cameraout val_data<10>
Project.unit<0>.triggerChannel<6><1>=cameraout val_data<1>
Project.unit<0>.triggerChannel<6><2>=cameraout val_data<2>
Project.unit<0>.triggerChannel<6><3>=cameraout val_data<3>
Project.unit<0>.triggerChannel<6><4>=cameraout val_data<4>
Project.unit<0>.triggerChannel<6><5>=cameraout val_data<5>
Project.unit<0>.triggerChannel<6><6>=cameraout val_data<6>
Project.unit<0>.triggerChannel<6><7>=cameraout val_data<7>
Project.unit<0>.triggerChannel<6><8>=cameraout val_data<8>
Project.unit<0>.triggerChannel<6><9>=cameraout val_data<9>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCount<4>=1
Project.unit<0>.triggerMatchCount<5>=1
Project.unit<0>.triggerMatchCount<6>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchCountWidth<4><0>=0
Project.unit<0>.triggerMatchCountWidth<5><0>=0
Project.unit<0>.triggerMatchCountWidth<6><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerMatchType<4><0>=1
Project.unit<0>.triggerMatchType<5><0>=1
Project.unit<0>.triggerMatchType<6><0>=1
Project.unit<0>.triggerPortCount=7
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortIsData<4>=true
Project.unit<0>.triggerPortIsData<5>=true
Project.unit<0>.triggerPortIsData<6>=true
Project.unit<0>.triggerPortWidth<0>=6
Project.unit<0>.triggerPortWidth<1>=1
Project.unit<0>.triggerPortWidth<2>=1
Project.unit<0>.triggerPortWidth<3>=1
Project.unit<0>.triggerPortWidth<4>=1
Project.unit<0>.triggerPortWidth<5>=8
Project.unit<0>.triggerPortWidth<6>=11
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
