#ChipScope Core Inserter Project File Version 3.0
#Sun Aug 14 22:53:33 CST 2016
Project.device.designInputFile=C\:\\14_ethernet_test\\14_ethernet_test\\ethernet_test_cs.ngc
Project.device.designOutputFile=C\:\\14_ethernet_test\\14_ethernet_test\\ethernet_test_cs.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=C\:\\14_ethernet_test\\14_ethernet_test\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=5
Project.filter<0>=*tx_total_length*
Project.filter<1>=*tx_data_length*
Project.filter<2>=*commmand_data*
Project.filter<3>=*clk*
Project.filter<4>=
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=contro camer_rdclk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=48
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=contro commmand_data<112>
Project.unit<0>.triggerChannel<0><10>=contro commmand_data<122>
Project.unit<0>.triggerChannel<0><11>=contro commmand_data<123>
Project.unit<0>.triggerChannel<0><12>=contro commmand_data<124>
Project.unit<0>.triggerChannel<0><13>=contro commmand_data<125>
Project.unit<0>.triggerChannel<0><14>=contro commmand_data<126>
Project.unit<0>.triggerChannel<0><15>=contro commmand_data<127>
Project.unit<0>.triggerChannel<0><1>=contro commmand_data<113>
Project.unit<0>.triggerChannel<0><2>=contro commmand_data<114>
Project.unit<0>.triggerChannel<0><3>=contro commmand_data<115>
Project.unit<0>.triggerChannel<0><4>=contro commmand_data<116>
Project.unit<0>.triggerChannel<0><5>=contro commmand_data<117>
Project.unit<0>.triggerChannel<0><6>=contro commmand_data<118>
Project.unit<0>.triggerChannel<0><7>=contro commmand_data<119>
Project.unit<0>.triggerChannel<0><8>=contro commmand_data<120>
Project.unit<0>.triggerChannel<0><9>=contro commmand_data<121>
Project.unit<0>.triggerChannel<1><0>=contro tx_data_length<0>
Project.unit<0>.triggerChannel<1><10>=contro tx_data_length<10>
Project.unit<0>.triggerChannel<1><11>=contro tx_data_length<11>
Project.unit<0>.triggerChannel<1><12>=contro tx_data_length<12>
Project.unit<0>.triggerChannel<1><13>=contro tx_data_length<13>
Project.unit<0>.triggerChannel<1><14>=contro tx_data_length<14>
Project.unit<0>.triggerChannel<1><15>=contro tx_data_length<15>
Project.unit<0>.triggerChannel<1><1>=contro tx_data_length<1>
Project.unit<0>.triggerChannel<1><2>=contro tx_data_length<2>
Project.unit<0>.triggerChannel<1><3>=contro tx_data_length<3>
Project.unit<0>.triggerChannel<1><4>=contro tx_data_length<4>
Project.unit<0>.triggerChannel<1><5>=contro tx_data_length<5>
Project.unit<0>.triggerChannel<1><6>=contro tx_data_length<6>
Project.unit<0>.triggerChannel<1><7>=contro tx_data_length<7>
Project.unit<0>.triggerChannel<1><8>=contro tx_data_length<8>
Project.unit<0>.triggerChannel<1><9>=contro tx_data_length<9>
Project.unit<0>.triggerChannel<2><0>=contro tx_total_length<0>
Project.unit<0>.triggerChannel<2><10>=contro tx_total_length<10>
Project.unit<0>.triggerChannel<2><11>=contro tx_total_length<11>
Project.unit<0>.triggerChannel<2><12>=contro tx_total_length<12>
Project.unit<0>.triggerChannel<2><13>=contro tx_total_length<13>
Project.unit<0>.triggerChannel<2><14>=contro tx_total_length<14>
Project.unit<0>.triggerChannel<2><15>=contro tx_total_length<15>
Project.unit<0>.triggerChannel<2><1>=contro tx_total_length<1>
Project.unit<0>.triggerChannel<2><2>=contro tx_total_length<2>
Project.unit<0>.triggerChannel<2><3>=contro tx_total_length<3>
Project.unit<0>.triggerChannel<2><4>=contro tx_total_length<4>
Project.unit<0>.triggerChannel<2><5>=contro tx_total_length<5>
Project.unit<0>.triggerChannel<2><6>=contro tx_total_length<6>
Project.unit<0>.triggerChannel<2><7>=contro tx_total_length<7>
Project.unit<0>.triggerChannel<2><8>=contro tx_total_length<8>
Project.unit<0>.triggerChannel<2><9>=contro tx_total_length<9>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerPortCount=3
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortWidth<0>=16
Project.unit<0>.triggerPortWidth<1>=16
Project.unit<0>.triggerPortWidth<2>=16
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
