#ChipScope Core Inserter Project File Version 3.0
#Sat Nov 19 15:30:01 CST 2016
Project.device.designInputFile=F\:\\theproject\\14_ethernet_test\\ethernet_test_cs.ngc
Project.device.designOutputFile=F\:\\theproject\\14_ethernet_test\\ethernet_test_cs.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=F\:\\theproject\\14_ethernet_test\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=9
Project.filter<0>=*data_o*
Project.filter<1>=*rx_*
Project.filter<2>=*rx_data*
Project.filter<3>=*rx_data_length*
Project.filter<4>=*rx_total_length*
Project.filter<5>=
Project.filter<6>=*state*
Project.filter<7>=*datain*
Project.filter<8>=*data*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=u1 iprecieve_inst clk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=u1 iprecieve_inst datain<0>
Project.unit<0>.dataChannel<10>=u1 rx_state<2>
Project.unit<0>.dataChannel<11>=u1 rx_state<3>
Project.unit<0>.dataChannel<1>=u1 iprecieve_inst datain<1>
Project.unit<0>.dataChannel<2>=u1 iprecieve_inst datain<2>
Project.unit<0>.dataChannel<3>=u1 iprecieve_inst datain<3>
Project.unit<0>.dataChannel<4>=u1 iprecieve_inst datain<4>
Project.unit<0>.dataChannel<5>=u1 iprecieve_inst datain<5>
Project.unit<0>.dataChannel<6>=u1 iprecieve_inst datain<6>
Project.unit<0>.dataChannel<7>=u1 iprecieve_inst datain<7>
Project.unit<0>.dataChannel<8>=u1 rx_state<0>
Project.unit<0>.dataChannel<9>=u1 rx_state<1>
Project.unit<0>.dataDepth=8192
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=77
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=u1 iprecieve_inst datain<0>
Project.unit<0>.triggerChannel<0><1>=u1 iprecieve_inst datain<1>
Project.unit<0>.triggerChannel<0><2>=u1 iprecieve_inst datain<2>
Project.unit<0>.triggerChannel<0><3>=u1 iprecieve_inst datain<3>
Project.unit<0>.triggerChannel<0><4>=u1 iprecieve_inst datain<4>
Project.unit<0>.triggerChannel<0><5>=u1 iprecieve_inst datain<5>
Project.unit<0>.triggerChannel<0><6>=u1 iprecieve_inst datain<6>
Project.unit<0>.triggerChannel<0><7>=u1 iprecieve_inst datain<7>
Project.unit<0>.triggerChannel<1><0>=u1 rx_state<0>
Project.unit<0>.triggerChannel<1><1>=u1 rx_state<1>
Project.unit<0>.triggerChannel<1><2>=u1 rx_state<2>
Project.unit<0>.triggerChannel<1><3>=u1 rx_state<3>
Project.unit<0>.triggerChannel<2><0>=u1 iprecieve_inst rx_total_length<0>
Project.unit<0>.triggerChannel<2><10>=u1 iprecieve_inst rx_total_length<10>
Project.unit<0>.triggerChannel<2><11>=u1 iprecieve_inst rx_total_length<11>
Project.unit<0>.triggerChannel<2><12>=u1 iprecieve_inst rx_total_length<12>
Project.unit<0>.triggerChannel<2><13>=u1 iprecieve_inst rx_total_length<13>
Project.unit<0>.triggerChannel<2><14>=u1 iprecieve_inst rx_total_length<14>
Project.unit<0>.triggerChannel<2><15>=u1 iprecieve_inst rx_total_length<15>
Project.unit<0>.triggerChannel<2><1>=u1 iprecieve_inst rx_total_length<1>
Project.unit<0>.triggerChannel<2><2>=u1 iprecieve_inst rx_total_length<2>
Project.unit<0>.triggerChannel<2><3>=u1 iprecieve_inst rx_total_length<3>
Project.unit<0>.triggerChannel<2><4>=u1 iprecieve_inst rx_total_length<4>
Project.unit<0>.triggerChannel<2><5>=u1 iprecieve_inst rx_total_length<5>
Project.unit<0>.triggerChannel<2><6>=u1 iprecieve_inst rx_total_length<6>
Project.unit<0>.triggerChannel<2><7>=u1 iprecieve_inst rx_total_length<7>
Project.unit<0>.triggerChannel<2><8>=u1 iprecieve_inst rx_total_length<8>
Project.unit<0>.triggerChannel<2><9>=u1 iprecieve_inst rx_total_length<9>
Project.unit<0>.triggerChannel<3><0>=u1 iprecieve_inst rx_total_length_reg<0>
Project.unit<0>.triggerChannel<3><10>=u1 iprecieve_inst rx_total_length_reg<10>
Project.unit<0>.triggerChannel<3><11>=u1 iprecieve_inst rx_total_length_reg<11>
Project.unit<0>.triggerChannel<3><12>=u1 iprecieve_inst rx_total_length_reg<12>
Project.unit<0>.triggerChannel<3><13>=u1 iprecieve_inst rx_total_length_reg<13>
Project.unit<0>.triggerChannel<3><14>=u1 iprecieve_inst rx_total_length_reg<14>
Project.unit<0>.triggerChannel<3><15>=u1 iprecieve_inst rx_total_length_reg<15>
Project.unit<0>.triggerChannel<3><1>=u1 iprecieve_inst rx_total_length_reg<1>
Project.unit<0>.triggerChannel<3><2>=u1 iprecieve_inst rx_total_length_reg<2>
Project.unit<0>.triggerChannel<3><3>=u1 iprecieve_inst rx_total_length_reg<3>
Project.unit<0>.triggerChannel<3><4>=u1 iprecieve_inst rx_total_length_reg<4>
Project.unit<0>.triggerChannel<3><5>=u1 iprecieve_inst rx_total_length_reg<5>
Project.unit<0>.triggerChannel<3><6>=u1 iprecieve_inst rx_total_length_reg<6>
Project.unit<0>.triggerChannel<3><7>=u1 iprecieve_inst rx_total_length_reg<7>
Project.unit<0>.triggerChannel<3><8>=u1 iprecieve_inst rx_total_length_reg<8>
Project.unit<0>.triggerChannel<3><9>=u1 iprecieve_inst rx_total_length_reg<9>
Project.unit<0>.triggerChannel<4><0>=u1 iprecieve_inst data_o<0>
Project.unit<0>.triggerChannel<4><10>=u1 iprecieve_inst data_o<10>
Project.unit<0>.triggerChannel<4><11>=u1 iprecieve_inst data_o<11>
Project.unit<0>.triggerChannel<4><12>=u1 iprecieve_inst data_o<12>
Project.unit<0>.triggerChannel<4><13>=u1 iprecieve_inst data_o<13>
Project.unit<0>.triggerChannel<4><14>=u1 iprecieve_inst data_o<14>
Project.unit<0>.triggerChannel<4><15>=u1 iprecieve_inst data_o<15>
Project.unit<0>.triggerChannel<4><16>=u1 iprecieve_inst data_o<16>
Project.unit<0>.triggerChannel<4><17>=u1 iprecieve_inst data_o<17>
Project.unit<0>.triggerChannel<4><18>=u1 iprecieve_inst data_o<18>
Project.unit<0>.triggerChannel<4><19>=u1 iprecieve_inst data_o<19>
Project.unit<0>.triggerChannel<4><1>=u1 iprecieve_inst data_o<1>
Project.unit<0>.triggerChannel<4><20>=u1 iprecieve_inst data_o<20>
Project.unit<0>.triggerChannel<4><21>=u1 iprecieve_inst data_o<21>
Project.unit<0>.triggerChannel<4><22>=u1 iprecieve_inst data_o<22>
Project.unit<0>.triggerChannel<4><23>=u1 iprecieve_inst data_o<23>
Project.unit<0>.triggerChannel<4><24>=u1 iprecieve_inst data_o<24>
Project.unit<0>.triggerChannel<4><25>=u1 iprecieve_inst data_o<25>
Project.unit<0>.triggerChannel<4><26>=u1 iprecieve_inst data_o<26>
Project.unit<0>.triggerChannel<4><27>=u1 iprecieve_inst data_o<27>
Project.unit<0>.triggerChannel<4><28>=u1 iprecieve_inst data_o<28>
Project.unit<0>.triggerChannel<4><29>=u1 iprecieve_inst data_o<29>
Project.unit<0>.triggerChannel<4><2>=u1 iprecieve_inst data_o<2>
Project.unit<0>.triggerChannel<4><30>=u1 iprecieve_inst data_o<30>
Project.unit<0>.triggerChannel<4><31>=u1 iprecieve_inst data_o<31>
Project.unit<0>.triggerChannel<4><3>=u1 iprecieve_inst data_o<3>
Project.unit<0>.triggerChannel<4><4>=u1 iprecieve_inst data_o<4>
Project.unit<0>.triggerChannel<4><5>=u1 iprecieve_inst data_o<5>
Project.unit<0>.triggerChannel<4><6>=u1 iprecieve_inst data_o<6>
Project.unit<0>.triggerChannel<4><7>=u1 iprecieve_inst data_o<7>
Project.unit<0>.triggerChannel<4><8>=u1 iprecieve_inst data_o<8>
Project.unit<0>.triggerChannel<4><9>=u1 iprecieve_inst data_o<9>
Project.unit<0>.triggerChannel<5><0>=u1 iprecieve_inst data_o_valid
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCount<4>=1
Project.unit<0>.triggerMatchCount<5>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchCountWidth<4><0>=0
Project.unit<0>.triggerMatchCountWidth<5><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerMatchType<4><0>=1
Project.unit<0>.triggerMatchType<5><0>=1
Project.unit<0>.triggerPortCount=6
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortIsData<4>=true
Project.unit<0>.triggerPortIsData<5>=true
Project.unit<0>.triggerPortWidth<0>=8
Project.unit<0>.triggerPortWidth<1>=4
Project.unit<0>.triggerPortWidth<2>=16
Project.unit<0>.triggerPortWidth<3>=16
Project.unit<0>.triggerPortWidth<4>=32
Project.unit<0>.triggerPortWidth<5>=1
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
