#ChipScope Core Inserter Project File Version 3.0
#Mon Nov 28 20:46:33 CST 2016
Project.device.designInputFile=F\:\\theproject\\14_ethernet_test\\ethernet_test_cs.ngc
Project.device.designOutputFile=F\:\\theproject\\14_ethernet_test\\ethernet_test_cs.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=F\:\\theproject\\14_ethernet_test\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=17
Project.filter<0>=*crcen*
Project.filter<10>=*txstate*
Project.filter<11>=*txen*
Project.filter<12>=*full*
Project.filter<13>=*empty*
Project.filter<14>=*tx_enable*
Project.filter<15>=*reset_n*
Project.filter<16>=*clk*
Project.filter<1>=*crcreset*
Project.filter<2>=
Project.filter<3>=*crc*
Project.filter<4>=*tx_total_length*
Project.filter<5>=*tx_data_length*
Project.filter<6>=*fifo_rden*
Project.filter<7>=*dataout*
Project.filter<8>=*fifo_dout*
Project.filter<9>=*tx_state*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=u1 ipsend_instance clk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=u1 ipsend_instance reset_n
Project.unit<0>.dataChannel<100>=u1 crc_inst CrcNext<12>
Project.unit<0>.dataChannel<101>=u1 crc_inst CrcNext<13>
Project.unit<0>.dataChannel<102>=u1 crc_inst CrcNext<14>
Project.unit<0>.dataChannel<103>=u1 crc_inst CrcNext<15>
Project.unit<0>.dataChannel<104>=u1 crc_inst CrcNext<16>
Project.unit<0>.dataChannel<105>=u1 crc_inst CrcNext<17>
Project.unit<0>.dataChannel<106>=u1 crc_inst CrcNext<18>
Project.unit<0>.dataChannel<107>=u1 crc_inst CrcNext<19>
Project.unit<0>.dataChannel<108>=u1 crc_inst CrcNext<20>
Project.unit<0>.dataChannel<109>=u1 crc_inst CrcNext<21>
Project.unit<0>.dataChannel<10>=u1 fifo_dout<3>
Project.unit<0>.dataChannel<110>=u1 crc_inst CrcNext<22>
Project.unit<0>.dataChannel<111>=u1 crc_inst CrcNext<23>
Project.unit<0>.dataChannel<112>=u1 crc_inst CrcNext<24>
Project.unit<0>.dataChannel<113>=u1 crc_inst CrcNext<25>
Project.unit<0>.dataChannel<114>=u1 crc_inst CrcNext<26>
Project.unit<0>.dataChannel<115>=u1 crc_inst CrcNext<27>
Project.unit<0>.dataChannel<116>=u1 crc_inst CrcNext<28>
Project.unit<0>.dataChannel<117>=u1 crc_inst CrcNext<29>
Project.unit<0>.dataChannel<118>=u1 crc_inst CrcNext<30>
Project.unit<0>.dataChannel<119>=u1 crc_inst CrcNext<31>
Project.unit<0>.dataChannel<11>=u1 fifo_dout<4>
Project.unit<0>.dataChannel<120>=u1 crcreset
Project.unit<0>.dataChannel<121>=u1 crcen
Project.unit<0>.dataChannel<12>=u1 fifo_dout<5>
Project.unit<0>.dataChannel<13>=u1 fifo_dout<6>
Project.unit<0>.dataChannel<14>=u1 fifo_dout<7>
Project.unit<0>.dataChannel<15>=u1 fifo_dout<8>
Project.unit<0>.dataChannel<16>=u1 fifo_dout<9>
Project.unit<0>.dataChannel<17>=u1 fifo_dout<10>
Project.unit<0>.dataChannel<18>=u1 fifo_dout<11>
Project.unit<0>.dataChannel<19>=u1 fifo_dout<12>
Project.unit<0>.dataChannel<1>=u1 ipsend_instance empty
Project.unit<0>.dataChannel<20>=u1 fifo_dout<13>
Project.unit<0>.dataChannel<21>=u1 fifo_dout<14>
Project.unit<0>.dataChannel<22>=u1 fifo_dout<15>
Project.unit<0>.dataChannel<23>=u1 fifo_dout<16>
Project.unit<0>.dataChannel<24>=u1 fifo_dout<17>
Project.unit<0>.dataChannel<25>=u1 fifo_dout<18>
Project.unit<0>.dataChannel<26>=u1 fifo_dout<19>
Project.unit<0>.dataChannel<27>=u1 fifo_dout<20>
Project.unit<0>.dataChannel<28>=u1 fifo_dout<21>
Project.unit<0>.dataChannel<29>=u1 fifo_dout<22>
Project.unit<0>.dataChannel<2>=u1 ipsend_instance txen
Project.unit<0>.dataChannel<30>=u1 fifo_dout<23>
Project.unit<0>.dataChannel<31>=u1 fifo_dout<24>
Project.unit<0>.dataChannel<32>=u1 fifo_dout<25>
Project.unit<0>.dataChannel<33>=u1 fifo_dout<26>
Project.unit<0>.dataChannel<34>=u1 fifo_dout<27>
Project.unit<0>.dataChannel<35>=u1 fifo_dout<28>
Project.unit<0>.dataChannel<36>=u1 fifo_dout<29>
Project.unit<0>.dataChannel<37>=u1 fifo_dout<30>
Project.unit<0>.dataChannel<38>=u1 fifo_dout<31>
Project.unit<0>.dataChannel<39>=u1 ipsend_instance dataout<0>
Project.unit<0>.dataChannel<3>=u1 tx_state<0>
Project.unit<0>.dataChannel<40>=u1 ipsend_instance dataout<1>
Project.unit<0>.dataChannel<41>=u1 ipsend_instance dataout<2>
Project.unit<0>.dataChannel<42>=u1 ipsend_instance dataout<3>
Project.unit<0>.dataChannel<43>=u1 ipsend_instance dataout<4>
Project.unit<0>.dataChannel<44>=u1 ipsend_instance dataout<5>
Project.unit<0>.dataChannel<45>=u1 ipsend_instance dataout<6>
Project.unit<0>.dataChannel<46>=u1 ipsend_instance dataout<7>
Project.unit<0>.dataChannel<47>=u1 ipsend_instance fifo_rden
Project.unit<0>.dataChannel<48>=u1 ipsend_instance tx_data_length<0>
Project.unit<0>.dataChannel<49>=u1 ipsend_instance tx_data_length<1>
Project.unit<0>.dataChannel<4>=u1 tx_state<1>
Project.unit<0>.dataChannel<50>=u1 ipsend_instance tx_data_length<2>
Project.unit<0>.dataChannel<51>=u1 ipsend_instance tx_data_length<3>
Project.unit<0>.dataChannel<52>=u1 ipsend_instance tx_data_length<4>
Project.unit<0>.dataChannel<53>=u1 ipsend_instance tx_data_length<5>
Project.unit<0>.dataChannel<54>=u1 ipsend_instance tx_data_length<6>
Project.unit<0>.dataChannel<55>=u1 ipsend_instance tx_data_length<7>
Project.unit<0>.dataChannel<56>=u1 ipsend_instance tx_data_length<8>
Project.unit<0>.dataChannel<57>=u1 ipsend_instance tx_data_length<9>
Project.unit<0>.dataChannel<58>=u1 ipsend_instance tx_data_length<10>
Project.unit<0>.dataChannel<59>=u1 ipsend_instance tx_data_length<11>
Project.unit<0>.dataChannel<5>=u1 tx_state<2>
Project.unit<0>.dataChannel<60>=u1 ipsend_instance tx_data_length<12>
Project.unit<0>.dataChannel<61>=u1 ipsend_instance tx_data_length<13>
Project.unit<0>.dataChannel<62>=u1 ipsend_instance tx_data_length<14>
Project.unit<0>.dataChannel<63>=u1 ipsend_instance tx_data_length<15>
Project.unit<0>.dataChannel<64>=u1 ipsend_instance tx_total_length<0>
Project.unit<0>.dataChannel<65>=u1 ipsend_instance tx_total_length<1>
Project.unit<0>.dataChannel<66>=u1 ipsend_instance tx_total_length<2>
Project.unit<0>.dataChannel<67>=u1 ipsend_instance tx_total_length<3>
Project.unit<0>.dataChannel<68>=u1 ipsend_instance tx_total_length<4>
Project.unit<0>.dataChannel<69>=u1 ipsend_instance tx_total_length<5>
Project.unit<0>.dataChannel<6>=u1 tx_state<3>
Project.unit<0>.dataChannel<70>=u1 ipsend_instance tx_total_length<6>
Project.unit<0>.dataChannel<71>=u1 ipsend_instance tx_total_length<7>
Project.unit<0>.dataChannel<72>=u1 ipsend_instance tx_total_length<8>
Project.unit<0>.dataChannel<73>=u1 ipsend_instance tx_total_length<9>
Project.unit<0>.dataChannel<74>=u1 ipsend_instance tx_total_length<10>
Project.unit<0>.dataChannel<75>=u1 ipsend_instance tx_total_length<11>
Project.unit<0>.dataChannel<76>=u1 ipsend_instance tx_total_length<12>
Project.unit<0>.dataChannel<77>=u1 ipsend_instance tx_total_length<13>
Project.unit<0>.dataChannel<78>=u1 ipsend_instance tx_total_length<14>
Project.unit<0>.dataChannel<79>=u1 ipsend_instance tx_total_length<15>
Project.unit<0>.dataChannel<7>=u1 fifo_dout<0>
Project.unit<0>.dataChannel<80>=u1 crc_inst Data_in<0>
Project.unit<0>.dataChannel<81>=u1 crc_inst Data_in<1>
Project.unit<0>.dataChannel<82>=u1 crc_inst Data_in<2>
Project.unit<0>.dataChannel<83>=u1 crc_inst Data_in<3>
Project.unit<0>.dataChannel<84>=u1 crc_inst Data_in<4>
Project.unit<0>.dataChannel<85>=u1 crc_inst Data_in<5>
Project.unit<0>.dataChannel<86>=u1 crc_inst Data_in<6>
Project.unit<0>.dataChannel<87>=u1 crc_inst Data_in<7>
Project.unit<0>.dataChannel<88>=u1 crc_inst CrcNext<0>
Project.unit<0>.dataChannel<89>=u1 crc_inst CrcNext<1>
Project.unit<0>.dataChannel<8>=u1 fifo_dout<1>
Project.unit<0>.dataChannel<90>=u1 crc_inst CrcNext<2>
Project.unit<0>.dataChannel<91>=u1 crc_inst CrcNext<3>
Project.unit<0>.dataChannel<92>=u1 crc_inst CrcNext<4>
Project.unit<0>.dataChannel<93>=u1 crc_inst CrcNext<5>
Project.unit<0>.dataChannel<94>=u1 crc_inst CrcNext<6>
Project.unit<0>.dataChannel<95>=u1 crc_inst CrcNext<7>
Project.unit<0>.dataChannel<96>=u1 crc_inst CrcNext<8>
Project.unit<0>.dataChannel<97>=u1 crc_inst CrcNext<9>
Project.unit<0>.dataChannel<98>=u1 crc_inst CrcNext<10>
Project.unit<0>.dataChannel<99>=u1 crc_inst CrcNext<11>
Project.unit<0>.dataChannel<9>=u1 fifo_dout<2>
Project.unit<0>.dataDepth=16384
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=122
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=u1 ipsend_instance reset_n
Project.unit<0>.triggerChannel<10><0>=u1 crc_inst CrcNext<0>
Project.unit<0>.triggerChannel<10><10>=u1 crc_inst CrcNext<10>
Project.unit<0>.triggerChannel<10><11>=u1 crc_inst CrcNext<11>
Project.unit<0>.triggerChannel<10><12>=u1 crc_inst CrcNext<12>
Project.unit<0>.triggerChannel<10><13>=u1 crc_inst CrcNext<13>
Project.unit<0>.triggerChannel<10><14>=u1 crc_inst CrcNext<14>
Project.unit<0>.triggerChannel<10><15>=u1 crc_inst CrcNext<15>
Project.unit<0>.triggerChannel<10><16>=u1 crc_inst CrcNext<16>
Project.unit<0>.triggerChannel<10><17>=u1 crc_inst CrcNext<17>
Project.unit<0>.triggerChannel<10><18>=u1 crc_inst CrcNext<18>
Project.unit<0>.triggerChannel<10><19>=u1 crc_inst CrcNext<19>
Project.unit<0>.triggerChannel<10><1>=u1 crc_inst CrcNext<1>
Project.unit<0>.triggerChannel<10><20>=u1 crc_inst CrcNext<20>
Project.unit<0>.triggerChannel<10><21>=u1 crc_inst CrcNext<21>
Project.unit<0>.triggerChannel<10><22>=u1 crc_inst CrcNext<22>
Project.unit<0>.triggerChannel<10><23>=u1 crc_inst CrcNext<23>
Project.unit<0>.triggerChannel<10><24>=u1 crc_inst CrcNext<24>
Project.unit<0>.triggerChannel<10><25>=u1 crc_inst CrcNext<25>
Project.unit<0>.triggerChannel<10><26>=u1 crc_inst CrcNext<26>
Project.unit<0>.triggerChannel<10><27>=u1 crc_inst CrcNext<27>
Project.unit<0>.triggerChannel<10><28>=u1 crc_inst CrcNext<28>
Project.unit<0>.triggerChannel<10><29>=u1 crc_inst CrcNext<29>
Project.unit<0>.triggerChannel<10><2>=u1 crc_inst CrcNext<2>
Project.unit<0>.triggerChannel<10><30>=u1 crc_inst CrcNext<30>
Project.unit<0>.triggerChannel<10><31>=u1 crc_inst CrcNext<31>
Project.unit<0>.triggerChannel<10><3>=u1 crc_inst CrcNext<3>
Project.unit<0>.triggerChannel<10><4>=u1 crc_inst CrcNext<4>
Project.unit<0>.triggerChannel<10><5>=u1 crc_inst CrcNext<5>
Project.unit<0>.triggerChannel<10><6>=u1 crc_inst CrcNext<6>
Project.unit<0>.triggerChannel<10><7>=u1 crc_inst CrcNext<7>
Project.unit<0>.triggerChannel<10><8>=u1 crc_inst CrcNext<8>
Project.unit<0>.triggerChannel<10><9>=u1 crc_inst CrcNext<9>
Project.unit<0>.triggerChannel<11><0>=u1 crcreset
Project.unit<0>.triggerChannel<12><0>=u1 crcen
Project.unit<0>.triggerChannel<1><0>=u1 ipsend_instance empty
Project.unit<0>.triggerChannel<2><0>=u1 ipsend_instance txen
Project.unit<0>.triggerChannel<3><0>=u1 tx_state<0>
Project.unit<0>.triggerChannel<3><1>=u1 tx_state<1>
Project.unit<0>.triggerChannel<3><2>=u1 tx_state<2>
Project.unit<0>.triggerChannel<3><3>=u1 tx_state<3>
Project.unit<0>.triggerChannel<4><0>=u1 fifo_dout<0>
Project.unit<0>.triggerChannel<4><10>=u1 fifo_dout<10>
Project.unit<0>.triggerChannel<4><11>=u1 fifo_dout<11>
Project.unit<0>.triggerChannel<4><12>=u1 fifo_dout<12>
Project.unit<0>.triggerChannel<4><13>=u1 fifo_dout<13>
Project.unit<0>.triggerChannel<4><14>=u1 fifo_dout<14>
Project.unit<0>.triggerChannel<4><15>=u1 fifo_dout<15>
Project.unit<0>.triggerChannel<4><16>=u1 fifo_dout<16>
Project.unit<0>.triggerChannel<4><17>=u1 fifo_dout<17>
Project.unit<0>.triggerChannel<4><18>=u1 fifo_dout<18>
Project.unit<0>.triggerChannel<4><19>=u1 fifo_dout<19>
Project.unit<0>.triggerChannel<4><1>=u1 fifo_dout<1>
Project.unit<0>.triggerChannel<4><20>=u1 fifo_dout<20>
Project.unit<0>.triggerChannel<4><21>=u1 fifo_dout<21>
Project.unit<0>.triggerChannel<4><22>=u1 fifo_dout<22>
Project.unit<0>.triggerChannel<4><23>=u1 fifo_dout<23>
Project.unit<0>.triggerChannel<4><24>=u1 fifo_dout<24>
Project.unit<0>.triggerChannel<4><25>=u1 fifo_dout<25>
Project.unit<0>.triggerChannel<4><26>=u1 fifo_dout<26>
Project.unit<0>.triggerChannel<4><27>=u1 fifo_dout<27>
Project.unit<0>.triggerChannel<4><28>=u1 fifo_dout<28>
Project.unit<0>.triggerChannel<4><29>=u1 fifo_dout<29>
Project.unit<0>.triggerChannel<4><2>=u1 fifo_dout<2>
Project.unit<0>.triggerChannel<4><30>=u1 fifo_dout<30>
Project.unit<0>.triggerChannel<4><31>=u1 fifo_dout<31>
Project.unit<0>.triggerChannel<4><3>=u1 fifo_dout<3>
Project.unit<0>.triggerChannel<4><4>=u1 fifo_dout<4>
Project.unit<0>.triggerChannel<4><5>=u1 fifo_dout<5>
Project.unit<0>.triggerChannel<4><6>=u1 fifo_dout<6>
Project.unit<0>.triggerChannel<4><7>=u1 fifo_dout<7>
Project.unit<0>.triggerChannel<4><8>=u1 fifo_dout<8>
Project.unit<0>.triggerChannel<4><9>=u1 fifo_dout<9>
Project.unit<0>.triggerChannel<5><0>=u1 ipsend_instance dataout<0>
Project.unit<0>.triggerChannel<5><1>=u1 ipsend_instance dataout<1>
Project.unit<0>.triggerChannel<5><2>=u1 ipsend_instance dataout<2>
Project.unit<0>.triggerChannel<5><3>=u1 ipsend_instance dataout<3>
Project.unit<0>.triggerChannel<5><4>=u1 ipsend_instance dataout<4>
Project.unit<0>.triggerChannel<5><5>=u1 ipsend_instance dataout<5>
Project.unit<0>.triggerChannel<5><6>=u1 ipsend_instance dataout<6>
Project.unit<0>.triggerChannel<5><7>=u1 ipsend_instance dataout<7>
Project.unit<0>.triggerChannel<6><0>=u1 ipsend_instance fifo_rden
Project.unit<0>.triggerChannel<7><0>=u1 ipsend_instance tx_data_length<0>
Project.unit<0>.triggerChannel<7><10>=u1 ipsend_instance tx_data_length<10>
Project.unit<0>.triggerChannel<7><11>=u1 ipsend_instance tx_data_length<11>
Project.unit<0>.triggerChannel<7><12>=u1 ipsend_instance tx_data_length<12>
Project.unit<0>.triggerChannel<7><13>=u1 ipsend_instance tx_data_length<13>
Project.unit<0>.triggerChannel<7><14>=u1 ipsend_instance tx_data_length<14>
Project.unit<0>.triggerChannel<7><15>=u1 ipsend_instance tx_data_length<15>
Project.unit<0>.triggerChannel<7><1>=u1 ipsend_instance tx_data_length<1>
Project.unit<0>.triggerChannel<7><2>=u1 ipsend_instance tx_data_length<2>
Project.unit<0>.triggerChannel<7><3>=u1 ipsend_instance tx_data_length<3>
Project.unit<0>.triggerChannel<7><4>=u1 ipsend_instance tx_data_length<4>
Project.unit<0>.triggerChannel<7><5>=u1 ipsend_instance tx_data_length<5>
Project.unit<0>.triggerChannel<7><6>=u1 ipsend_instance tx_data_length<6>
Project.unit<0>.triggerChannel<7><7>=u1 ipsend_instance tx_data_length<7>
Project.unit<0>.triggerChannel<7><8>=u1 ipsend_instance tx_data_length<8>
Project.unit<0>.triggerChannel<7><9>=u1 ipsend_instance tx_data_length<9>
Project.unit<0>.triggerChannel<8><0>=u1 ipsend_instance tx_total_length<0>
Project.unit<0>.triggerChannel<8><10>=u1 ipsend_instance tx_total_length<10>
Project.unit<0>.triggerChannel<8><11>=u1 ipsend_instance tx_total_length<11>
Project.unit<0>.triggerChannel<8><12>=u1 ipsend_instance tx_total_length<12>
Project.unit<0>.triggerChannel<8><13>=u1 ipsend_instance tx_total_length<13>
Project.unit<0>.triggerChannel<8><14>=u1 ipsend_instance tx_total_length<14>
Project.unit<0>.triggerChannel<8><15>=u1 ipsend_instance tx_total_length<15>
Project.unit<0>.triggerChannel<8><1>=u1 ipsend_instance tx_total_length<1>
Project.unit<0>.triggerChannel<8><2>=u1 ipsend_instance tx_total_length<2>
Project.unit<0>.triggerChannel<8><3>=u1 ipsend_instance tx_total_length<3>
Project.unit<0>.triggerChannel<8><4>=u1 ipsend_instance tx_total_length<4>
Project.unit<0>.triggerChannel<8><5>=u1 ipsend_instance tx_total_length<5>
Project.unit<0>.triggerChannel<8><6>=u1 ipsend_instance tx_total_length<6>
Project.unit<0>.triggerChannel<8><7>=u1 ipsend_instance tx_total_length<7>
Project.unit<0>.triggerChannel<8><8>=u1 ipsend_instance tx_total_length<8>
Project.unit<0>.triggerChannel<8><9>=u1 ipsend_instance tx_total_length<9>
Project.unit<0>.triggerChannel<9><0>=u1 crc_inst Data_in<0>
Project.unit<0>.triggerChannel<9><1>=u1 crc_inst Data_in<1>
Project.unit<0>.triggerChannel<9><2>=u1 crc_inst Data_in<2>
Project.unit<0>.triggerChannel<9><3>=u1 crc_inst Data_in<3>
Project.unit<0>.triggerChannel<9><4>=u1 crc_inst Data_in<4>
Project.unit<0>.triggerChannel<9><5>=u1 crc_inst Data_in<5>
Project.unit<0>.triggerChannel<9><6>=u1 crc_inst Data_in<6>
Project.unit<0>.triggerChannel<9><7>=u1 crc_inst Data_in<7>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<10>=1
Project.unit<0>.triggerMatchCount<11>=1
Project.unit<0>.triggerMatchCount<12>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCount<4>=1
Project.unit<0>.triggerMatchCount<5>=1
Project.unit<0>.triggerMatchCount<6>=1
Project.unit<0>.triggerMatchCount<7>=1
Project.unit<0>.triggerMatchCount<8>=1
Project.unit<0>.triggerMatchCount<9>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<10><0>=0
Project.unit<0>.triggerMatchCountWidth<11><0>=0
Project.unit<0>.triggerMatchCountWidth<12><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchCountWidth<4><0>=0
Project.unit<0>.triggerMatchCountWidth<5><0>=0
Project.unit<0>.triggerMatchCountWidth<6><0>=0
Project.unit<0>.triggerMatchCountWidth<7><0>=0
Project.unit<0>.triggerMatchCountWidth<8><0>=0
Project.unit<0>.triggerMatchCountWidth<9><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<10><0>=1
Project.unit<0>.triggerMatchType<11><0>=1
Project.unit<0>.triggerMatchType<12><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerMatchType<4><0>=1
Project.unit<0>.triggerMatchType<5><0>=1
Project.unit<0>.triggerMatchType<6><0>=1
Project.unit<0>.triggerMatchType<7><0>=1
Project.unit<0>.triggerMatchType<8><0>=1
Project.unit<0>.triggerMatchType<9><0>=1
Project.unit<0>.triggerPortCount=13
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<10>=true
Project.unit<0>.triggerPortIsData<11>=true
Project.unit<0>.triggerPortIsData<12>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortIsData<4>=true
Project.unit<0>.triggerPortIsData<5>=true
Project.unit<0>.triggerPortIsData<6>=true
Project.unit<0>.triggerPortIsData<7>=true
Project.unit<0>.triggerPortIsData<8>=true
Project.unit<0>.triggerPortIsData<9>=true
Project.unit<0>.triggerPortWidth<0>=1
Project.unit<0>.triggerPortWidth<10>=32
Project.unit<0>.triggerPortWidth<11>=1
Project.unit<0>.triggerPortWidth<12>=1
Project.unit<0>.triggerPortWidth<1>=1
Project.unit<0>.triggerPortWidth<2>=1
Project.unit<0>.triggerPortWidth<3>=4
Project.unit<0>.triggerPortWidth<4>=32
Project.unit<0>.triggerPortWidth<5>=8
Project.unit<0>.triggerPortWidth<6>=1
Project.unit<0>.triggerPortWidth<7>=16
Project.unit<0>.triggerPortWidth<8>=16
Project.unit<0>.triggerPortWidth<9>=8
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
