#ChipScope Core Inserter Project File Version 3.0
#Tue Aug 09 19:56:30 CST 2016
Project.device.designInputFile=C\:\\14_ethernet_test\\14_ethernet_test\\ethernet_test_cs.ngc
Project.device.designOutputFile=C\:\\14_ethernet_test\\14_ethernet_test\\ethernet_test_cs.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=C\:\\14_ethernet_test\\14_ethernet_test\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=*fifo_empty*
Project.filter<10>=*etx_din*
Project.filter<11>=*ewr_en*
Project.filter<12>=*etx_full*
Project.filter<13>=*commmand_data_reg*
Project.filter<14>=*command_data*
Project.filter<15>=*commanddata*
Project.filter<16>=*conmanddata*
Project.filter<17>=*clk*
Project.filter<18>=*reset*
Project.filter<1>=*ddr3_wren*
Project.filter<2>=*ddr3_data*
Project.filter<3>=*e_rd_en*
Project.filter<4>=*ddr3_full*
Project.filter<5>=*empty*
Project.filter<6>=*data_in*
Project.filter<7>=
Project.filter<8>=*tx_total_length*
Project.filter<9>=*tx_data_length*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=clk_50MHz
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=contro data_in<0>
Project.unit<0>.dataChannel<100>=contro ddr3_data<29>
Project.unit<0>.dataChannel<101>=contro ddr3_data<30>
Project.unit<0>.dataChannel<102>=contro ddr3_data<31>
Project.unit<0>.dataChannel<103>=contro ddr3_data<32>
Project.unit<0>.dataChannel<104>=contro ddr3_data<33>
Project.unit<0>.dataChannel<105>=contro ddr3_data<34>
Project.unit<0>.dataChannel<106>=contro ddr3_data<35>
Project.unit<0>.dataChannel<107>=contro ddr3_data<36>
Project.unit<0>.dataChannel<108>=contro ddr3_data<37>
Project.unit<0>.dataChannel<109>=contro ddr3_data<38>
Project.unit<0>.dataChannel<10>=contro data_in<10>
Project.unit<0>.dataChannel<110>=contro ddr3_data<39>
Project.unit<0>.dataChannel<111>=contro ddr3_data<40>
Project.unit<0>.dataChannel<112>=contro ddr3_data<41>
Project.unit<0>.dataChannel<113>=contro ddr3_data<42>
Project.unit<0>.dataChannel<114>=contro ddr3_data<43>
Project.unit<0>.dataChannel<115>=contro ddr3_data<44>
Project.unit<0>.dataChannel<116>=contro ddr3_data<45>
Project.unit<0>.dataChannel<117>=contro ddr3_data<46>
Project.unit<0>.dataChannel<118>=contro ddr3_data<47>
Project.unit<0>.dataChannel<119>=contro ddr3_data<48>
Project.unit<0>.dataChannel<11>=contro data_in<11>
Project.unit<0>.dataChannel<120>=contro ddr3_data<49>
Project.unit<0>.dataChannel<121>=contro ddr3_data<50>
Project.unit<0>.dataChannel<122>=contro ddr3_data<51>
Project.unit<0>.dataChannel<123>=contro ddr3_data<52>
Project.unit<0>.dataChannel<124>=contro ddr3_data<53>
Project.unit<0>.dataChannel<125>=contro ddr3_data<54>
Project.unit<0>.dataChannel<126>=contro ddr3_data<55>
Project.unit<0>.dataChannel<127>=contro ddr3_data<56>
Project.unit<0>.dataChannel<128>=contro ddr3_data<57>
Project.unit<0>.dataChannel<129>=contro ddr3_data<58>
Project.unit<0>.dataChannel<12>=contro data_in<12>
Project.unit<0>.dataChannel<130>=contro ddr3_data<59>
Project.unit<0>.dataChannel<131>=contro ddr3_data<60>
Project.unit<0>.dataChannel<132>=contro ddr3_data<61>
Project.unit<0>.dataChannel<133>=contro ddr3_data<62>
Project.unit<0>.dataChannel<134>=contro ddr3_data<63>
Project.unit<0>.dataChannel<135>=contro ddr3_wren
Project.unit<0>.dataChannel<136>=ddr_con_c3 fifo_empty
Project.unit<0>.dataChannel<13>=contro data_in<13>
Project.unit<0>.dataChannel<14>=contro data_in<14>
Project.unit<0>.dataChannel<15>=contro data_in<15>
Project.unit<0>.dataChannel<16>=contro data_in<16>
Project.unit<0>.dataChannel<17>=contro data_in<17>
Project.unit<0>.dataChannel<18>=contro data_in<18>
Project.unit<0>.dataChannel<19>=contro data_in<19>
Project.unit<0>.dataChannel<1>=contro data_in<1>
Project.unit<0>.dataChannel<20>=contro data_in<20>
Project.unit<0>.dataChannel<21>=contro data_in<21>
Project.unit<0>.dataChannel<22>=contro data_in<22>
Project.unit<0>.dataChannel<23>=contro data_in<23>
Project.unit<0>.dataChannel<24>=contro data_in<24>
Project.unit<0>.dataChannel<25>=contro data_in<25>
Project.unit<0>.dataChannel<26>=contro data_in<26>
Project.unit<0>.dataChannel<27>=contro data_in<27>
Project.unit<0>.dataChannel<28>=contro data_in<28>
Project.unit<0>.dataChannel<29>=contro data_in<29>
Project.unit<0>.dataChannel<2>=contro data_in<2>
Project.unit<0>.dataChannel<30>=contro data_in<30>
Project.unit<0>.dataChannel<31>=contro data_in<31>
Project.unit<0>.dataChannel<32>=contro data_in<32>
Project.unit<0>.dataChannel<33>=contro data_in<33>
Project.unit<0>.dataChannel<34>=contro data_in<34>
Project.unit<0>.dataChannel<35>=contro data_in<35>
Project.unit<0>.dataChannel<36>=contro data_in<36>
Project.unit<0>.dataChannel<37>=contro data_in<37>
Project.unit<0>.dataChannel<38>=contro data_in<38>
Project.unit<0>.dataChannel<39>=contro data_in<39>
Project.unit<0>.dataChannel<3>=contro data_in<3>
Project.unit<0>.dataChannel<40>=contro data_in<40>
Project.unit<0>.dataChannel<41>=contro data_in<41>
Project.unit<0>.dataChannel<42>=contro data_in<42>
Project.unit<0>.dataChannel<43>=contro data_in<43>
Project.unit<0>.dataChannel<44>=contro data_in<44>
Project.unit<0>.dataChannel<45>=contro data_in<45>
Project.unit<0>.dataChannel<46>=contro data_in<46>
Project.unit<0>.dataChannel<47>=contro data_in<47>
Project.unit<0>.dataChannel<48>=contro data_in<48>
Project.unit<0>.dataChannel<49>=contro data_in<49>
Project.unit<0>.dataChannel<4>=contro data_in<4>
Project.unit<0>.dataChannel<50>=contro data_in<50>
Project.unit<0>.dataChannel<51>=contro data_in<51>
Project.unit<0>.dataChannel<52>=contro data_in<52>
Project.unit<0>.dataChannel<53>=contro data_in<53>
Project.unit<0>.dataChannel<54>=contro data_in<54>
Project.unit<0>.dataChannel<55>=contro data_in<55>
Project.unit<0>.dataChannel<56>=contro data_in<56>
Project.unit<0>.dataChannel<57>=contro data_in<57>
Project.unit<0>.dataChannel<58>=contro data_in<58>
Project.unit<0>.dataChannel<59>=contro data_in<59>
Project.unit<0>.dataChannel<5>=contro data_in<5>
Project.unit<0>.dataChannel<60>=contro data_in<60>
Project.unit<0>.dataChannel<61>=contro data_in<61>
Project.unit<0>.dataChannel<62>=contro data_in<62>
Project.unit<0>.dataChannel<63>=contro data_in<63>
Project.unit<0>.dataChannel<64>=u1 rx_state<0>
Project.unit<0>.dataChannel<65>=u1 rx_state<1>
Project.unit<0>.dataChannel<66>=u1 rx_state<2>
Project.unit<0>.dataChannel<67>=u1 rx_state<3>
Project.unit<0>.dataChannel<68>=contro empty
Project.unit<0>.dataChannel<69>=contro ddr3_full
Project.unit<0>.dataChannel<6>=contro data_in<6>
Project.unit<0>.dataChannel<70>=contro e_rd_en
Project.unit<0>.dataChannel<71>=contro ddr3_data<0>
Project.unit<0>.dataChannel<72>=contro ddr3_data<1>
Project.unit<0>.dataChannel<73>=contro ddr3_data<2>
Project.unit<0>.dataChannel<74>=contro ddr3_data<3>
Project.unit<0>.dataChannel<75>=contro ddr3_data<4>
Project.unit<0>.dataChannel<76>=contro ddr3_data<5>
Project.unit<0>.dataChannel<77>=contro ddr3_data<6>
Project.unit<0>.dataChannel<78>=contro ddr3_data<7>
Project.unit<0>.dataChannel<79>=contro ddr3_data<8>
Project.unit<0>.dataChannel<7>=contro data_in<7>
Project.unit<0>.dataChannel<80>=contro ddr3_data<9>
Project.unit<0>.dataChannel<81>=contro ddr3_data<10>
Project.unit<0>.dataChannel<82>=contro ddr3_data<11>
Project.unit<0>.dataChannel<83>=contro ddr3_data<12>
Project.unit<0>.dataChannel<84>=contro ddr3_data<13>
Project.unit<0>.dataChannel<85>=contro ddr3_data<14>
Project.unit<0>.dataChannel<86>=contro ddr3_data<15>
Project.unit<0>.dataChannel<87>=contro ddr3_data<16>
Project.unit<0>.dataChannel<88>=contro ddr3_data<17>
Project.unit<0>.dataChannel<89>=contro ddr3_data<18>
Project.unit<0>.dataChannel<8>=contro data_in<8>
Project.unit<0>.dataChannel<90>=contro ddr3_data<19>
Project.unit<0>.dataChannel<91>=contro ddr3_data<20>
Project.unit<0>.dataChannel<92>=contro ddr3_data<21>
Project.unit<0>.dataChannel<93>=contro ddr3_data<22>
Project.unit<0>.dataChannel<94>=contro ddr3_data<23>
Project.unit<0>.dataChannel<95>=contro ddr3_data<24>
Project.unit<0>.dataChannel<96>=contro ddr3_data<25>
Project.unit<0>.dataChannel<97>=contro ddr3_data<26>
Project.unit<0>.dataChannel<98>=contro ddr3_data<27>
Project.unit<0>.dataChannel<99>=contro ddr3_data<28>
Project.unit<0>.dataChannel<9>=contro data_in<9>
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=136
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=contro data_in<0>
Project.unit<0>.triggerChannel<0><10>=contro data_in<10>
Project.unit<0>.triggerChannel<0><11>=contro data_in<11>
Project.unit<0>.triggerChannel<0><12>=contro data_in<12>
Project.unit<0>.triggerChannel<0><13>=contro data_in<13>
Project.unit<0>.triggerChannel<0><14>=contro data_in<14>
Project.unit<0>.triggerChannel<0><15>=contro data_in<15>
Project.unit<0>.triggerChannel<0><16>=contro data_in<16>
Project.unit<0>.triggerChannel<0><17>=contro data_in<17>
Project.unit<0>.triggerChannel<0><18>=contro data_in<18>
Project.unit<0>.triggerChannel<0><19>=contro data_in<19>
Project.unit<0>.triggerChannel<0><1>=contro data_in<1>
Project.unit<0>.triggerChannel<0><20>=contro data_in<20>
Project.unit<0>.triggerChannel<0><21>=contro data_in<21>
Project.unit<0>.triggerChannel<0><22>=contro data_in<22>
Project.unit<0>.triggerChannel<0><23>=contro data_in<23>
Project.unit<0>.triggerChannel<0><24>=contro data_in<24>
Project.unit<0>.triggerChannel<0><25>=contro data_in<25>
Project.unit<0>.triggerChannel<0><26>=contro data_in<26>
Project.unit<0>.triggerChannel<0><27>=contro data_in<27>
Project.unit<0>.triggerChannel<0><28>=contro data_in<28>
Project.unit<0>.triggerChannel<0><29>=contro data_in<29>
Project.unit<0>.triggerChannel<0><2>=contro data_in<2>
Project.unit<0>.triggerChannel<0><30>=contro data_in<30>
Project.unit<0>.triggerChannel<0><31>=contro data_in<31>
Project.unit<0>.triggerChannel<0><32>=contro data_in<32>
Project.unit<0>.triggerChannel<0><33>=contro data_in<33>
Project.unit<0>.triggerChannel<0><34>=contro data_in<34>
Project.unit<0>.triggerChannel<0><35>=contro data_in<35>
Project.unit<0>.triggerChannel<0><36>=contro data_in<36>
Project.unit<0>.triggerChannel<0><37>=contro data_in<37>
Project.unit<0>.triggerChannel<0><38>=contro data_in<38>
Project.unit<0>.triggerChannel<0><39>=contro data_in<39>
Project.unit<0>.triggerChannel<0><3>=contro data_in<3>
Project.unit<0>.triggerChannel<0><40>=contro data_in<40>
Project.unit<0>.triggerChannel<0><41>=contro data_in<41>
Project.unit<0>.triggerChannel<0><42>=contro data_in<42>
Project.unit<0>.triggerChannel<0><43>=contro data_in<43>
Project.unit<0>.triggerChannel<0><44>=contro data_in<44>
Project.unit<0>.triggerChannel<0><45>=contro data_in<45>
Project.unit<0>.triggerChannel<0><46>=contro data_in<46>
Project.unit<0>.triggerChannel<0><47>=contro data_in<47>
Project.unit<0>.triggerChannel<0><48>=contro data_in<48>
Project.unit<0>.triggerChannel<0><49>=contro data_in<49>
Project.unit<0>.triggerChannel<0><4>=contro data_in<4>
Project.unit<0>.triggerChannel<0><50>=contro data_in<50>
Project.unit<0>.triggerChannel<0><51>=contro data_in<51>
Project.unit<0>.triggerChannel<0><52>=contro data_in<52>
Project.unit<0>.triggerChannel<0><53>=contro data_in<53>
Project.unit<0>.triggerChannel<0><54>=contro data_in<54>
Project.unit<0>.triggerChannel<0><55>=contro data_in<55>
Project.unit<0>.triggerChannel<0><56>=contro data_in<56>
Project.unit<0>.triggerChannel<0><57>=contro data_in<57>
Project.unit<0>.triggerChannel<0><58>=contro data_in<58>
Project.unit<0>.triggerChannel<0><59>=contro data_in<59>
Project.unit<0>.triggerChannel<0><5>=contro data_in<5>
Project.unit<0>.triggerChannel<0><60>=contro data_in<60>
Project.unit<0>.triggerChannel<0><61>=contro data_in<61>
Project.unit<0>.triggerChannel<0><62>=contro data_in<62>
Project.unit<0>.triggerChannel<0><63>=contro data_in<63>
Project.unit<0>.triggerChannel<0><6>=contro data_in<6>
Project.unit<0>.triggerChannel<0><7>=contro data_in<7>
Project.unit<0>.triggerChannel<0><8>=contro data_in<8>
Project.unit<0>.triggerChannel<0><9>=contro data_in<9>
Project.unit<0>.triggerChannel<1><0>=u1 rx_state<0>
Project.unit<0>.triggerChannel<1><1>=u1 rx_state<1>
Project.unit<0>.triggerChannel<1><2>=u1 rx_state<2>
Project.unit<0>.triggerChannel<1><3>=u1 rx_state<3>
Project.unit<0>.triggerChannel<2><0>=contro empty
Project.unit<0>.triggerChannel<3><0>=contro ddr3_full
Project.unit<0>.triggerChannel<4><0>=contro e_rd_en
Project.unit<0>.triggerChannel<5><0>=contro ddr3_data<0>
Project.unit<0>.triggerChannel<5><10>=contro ddr3_data<10>
Project.unit<0>.triggerChannel<5><11>=contro ddr3_data<11>
Project.unit<0>.triggerChannel<5><12>=contro ddr3_data<12>
Project.unit<0>.triggerChannel<5><13>=contro ddr3_data<13>
Project.unit<0>.triggerChannel<5><14>=contro ddr3_data<14>
Project.unit<0>.triggerChannel<5><15>=contro ddr3_data<15>
Project.unit<0>.triggerChannel<5><16>=contro ddr3_data<16>
Project.unit<0>.triggerChannel<5><17>=contro ddr3_data<17>
Project.unit<0>.triggerChannel<5><18>=contro ddr3_data<18>
Project.unit<0>.triggerChannel<5><19>=contro ddr3_data<19>
Project.unit<0>.triggerChannel<5><1>=contro ddr3_data<1>
Project.unit<0>.triggerChannel<5><20>=contro ddr3_data<20>
Project.unit<0>.triggerChannel<5><21>=contro ddr3_data<21>
Project.unit<0>.triggerChannel<5><22>=contro ddr3_data<22>
Project.unit<0>.triggerChannel<5><23>=contro ddr3_data<23>
Project.unit<0>.triggerChannel<5><24>=contro ddr3_data<24>
Project.unit<0>.triggerChannel<5><25>=contro ddr3_data<25>
Project.unit<0>.triggerChannel<5><26>=contro ddr3_data<26>
Project.unit<0>.triggerChannel<5><27>=contro ddr3_data<27>
Project.unit<0>.triggerChannel<5><28>=contro ddr3_data<28>
Project.unit<0>.triggerChannel<5><29>=contro ddr3_data<29>
Project.unit<0>.triggerChannel<5><2>=contro ddr3_data<2>
Project.unit<0>.triggerChannel<5><30>=contro ddr3_data<30>
Project.unit<0>.triggerChannel<5><31>=contro ddr3_data<31>
Project.unit<0>.triggerChannel<5><32>=contro ddr3_data<32>
Project.unit<0>.triggerChannel<5><33>=contro ddr3_data<33>
Project.unit<0>.triggerChannel<5><34>=contro ddr3_data<34>
Project.unit<0>.triggerChannel<5><35>=contro ddr3_data<35>
Project.unit<0>.triggerChannel<5><36>=contro ddr3_data<36>
Project.unit<0>.triggerChannel<5><37>=contro ddr3_data<37>
Project.unit<0>.triggerChannel<5><38>=contro ddr3_data<38>
Project.unit<0>.triggerChannel<5><39>=contro ddr3_data<39>
Project.unit<0>.triggerChannel<5><3>=contro ddr3_data<3>
Project.unit<0>.triggerChannel<5><40>=contro ddr3_data<40>
Project.unit<0>.triggerChannel<5><41>=contro ddr3_data<41>
Project.unit<0>.triggerChannel<5><42>=contro ddr3_data<42>
Project.unit<0>.triggerChannel<5><43>=contro ddr3_data<43>
Project.unit<0>.triggerChannel<5><44>=contro ddr3_data<44>
Project.unit<0>.triggerChannel<5><45>=contro ddr3_data<45>
Project.unit<0>.triggerChannel<5><46>=contro ddr3_data<46>
Project.unit<0>.triggerChannel<5><47>=contro ddr3_data<47>
Project.unit<0>.triggerChannel<5><48>=contro ddr3_data<48>
Project.unit<0>.triggerChannel<5><49>=contro ddr3_data<49>
Project.unit<0>.triggerChannel<5><4>=contro ddr3_data<4>
Project.unit<0>.triggerChannel<5><50>=contro ddr3_data<50>
Project.unit<0>.triggerChannel<5><51>=contro ddr3_data<51>
Project.unit<0>.triggerChannel<5><52>=contro ddr3_data<52>
Project.unit<0>.triggerChannel<5><53>=contro ddr3_data<53>
Project.unit<0>.triggerChannel<5><54>=contro ddr3_data<54>
Project.unit<0>.triggerChannel<5><55>=contro ddr3_data<55>
Project.unit<0>.triggerChannel<5><56>=contro ddr3_data<56>
Project.unit<0>.triggerChannel<5><57>=contro ddr3_data<57>
Project.unit<0>.triggerChannel<5><58>=contro ddr3_data<58>
Project.unit<0>.triggerChannel<5><59>=contro ddr3_data<59>
Project.unit<0>.triggerChannel<5><5>=contro ddr3_data<5>
Project.unit<0>.triggerChannel<5><60>=contro ddr3_data<60>
Project.unit<0>.triggerChannel<5><61>=contro ddr3_data<61>
Project.unit<0>.triggerChannel<5><62>=contro ddr3_data<62>
Project.unit<0>.triggerChannel<5><63>=contro ddr3_data<63>
Project.unit<0>.triggerChannel<5><6>=contro ddr3_data<6>
Project.unit<0>.triggerChannel<5><7>=contro ddr3_data<7>
Project.unit<0>.triggerChannel<5><8>=contro ddr3_data<8>
Project.unit<0>.triggerChannel<5><9>=contro ddr3_data<9>
Project.unit<0>.triggerChannel<6><0>=contro ddr3_wren
Project.unit<0>.triggerChannel<7><0>=ddr_con_c3 fifo_empty
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCount<4>=1
Project.unit<0>.triggerMatchCount<5>=1
Project.unit<0>.triggerMatchCount<6>=1
Project.unit<0>.triggerMatchCount<7>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchCountWidth<4><0>=0
Project.unit<0>.triggerMatchCountWidth<5><0>=0
Project.unit<0>.triggerMatchCountWidth<6><0>=0
Project.unit<0>.triggerMatchCountWidth<7><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerMatchType<4><0>=1
Project.unit<0>.triggerMatchType<5><0>=1
Project.unit<0>.triggerMatchType<6><0>=1
Project.unit<0>.triggerMatchType<7><0>=1
Project.unit<0>.triggerPortCount=7
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortIsData<4>=true
Project.unit<0>.triggerPortIsData<5>=true
Project.unit<0>.triggerPortIsData<6>=true
Project.unit<0>.triggerPortIsData<7>=true
Project.unit<0>.triggerPortWidth<0>=64
Project.unit<0>.triggerPortWidth<1>=4
Project.unit<0>.triggerPortWidth<2>=1
Project.unit<0>.triggerPortWidth<3>=1
Project.unit<0>.triggerPortWidth<4>=1
Project.unit<0>.triggerPortWidth<5>=64
Project.unit<0>.triggerPortWidth<6>=1
Project.unit<0>.triggerPortWidth<7>=1
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
