#ChipScope Core Inserter Project File Version 3.0
#Tue Nov 08 15:05:12 CST 2016
Project.device.designInputFile=F\:\\theproject\\14_ethernet_test\\ethernet_test_cs.ngc
Project.device.designOutputFile=F\:\\theproject\\14_ethernet_test\\ethernet_test_cs.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=F\:\\theproject\\14_ethernet_test\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=9
Project.filter<0>=*e_rd_en_reg*
Project.filter<1>=*ewr_en*
Project.filter<2>=*e_rd_en_o*
Project.filter<3>=
Project.filter<4>=*etx_din*
Project.filter<5>=*data_in*
Project.filter<6>=data_in
Project.filter<7>=data
Project.filter<8>=clk
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=contro U2 clk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataDepth=2048
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=146
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=contro U2 data_in<0>
Project.unit<0>.triggerChannel<0><10>=contro U2 data_in<10>
Project.unit<0>.triggerChannel<0><11>=contro U2 data_in<11>
Project.unit<0>.triggerChannel<0><12>=contro U2 data_in<12>
Project.unit<0>.triggerChannel<0><13>=contro U2 data_in<13>
Project.unit<0>.triggerChannel<0><14>=contro U2 data_in<14>
Project.unit<0>.triggerChannel<0><15>=contro U2 data_in<15>
Project.unit<0>.triggerChannel<0><16>=contro U2 data_in<16>
Project.unit<0>.triggerChannel<0><17>=contro U2 data_in<17>
Project.unit<0>.triggerChannel<0><18>=contro U2 data_in<18>
Project.unit<0>.triggerChannel<0><19>=contro U2 data_in<19>
Project.unit<0>.triggerChannel<0><1>=contro U2 data_in<1>
Project.unit<0>.triggerChannel<0><20>=contro U2 data_in<20>
Project.unit<0>.triggerChannel<0><21>=contro U2 data_in<21>
Project.unit<0>.triggerChannel<0><22>=contro U2 data_in<22>
Project.unit<0>.triggerChannel<0><23>=contro U2 data_in<23>
Project.unit<0>.triggerChannel<0><24>=contro U2 data_in<24>
Project.unit<0>.triggerChannel<0><25>=contro U2 data_in<25>
Project.unit<0>.triggerChannel<0><26>=contro U2 data_in<26>
Project.unit<0>.triggerChannel<0><27>=contro U2 data_in<27>
Project.unit<0>.triggerChannel<0><28>=contro U2 data_in<28>
Project.unit<0>.triggerChannel<0><29>=contro U2 data_in<29>
Project.unit<0>.triggerChannel<0><2>=contro U2 data_in<2>
Project.unit<0>.triggerChannel<0><30>=contro U2 data_in<30>
Project.unit<0>.triggerChannel<0><31>=contro U2 data_in<31>
Project.unit<0>.triggerChannel<0><32>=contro U2 data_in<32>
Project.unit<0>.triggerChannel<0><33>=contro U2 data_in<33>
Project.unit<0>.triggerChannel<0><34>=contro U2 data_in<34>
Project.unit<0>.triggerChannel<0><35>=contro U2 data_in<35>
Project.unit<0>.triggerChannel<0><36>=contro U2 data_in<36>
Project.unit<0>.triggerChannel<0><37>=contro U2 data_in<37>
Project.unit<0>.triggerChannel<0><38>=contro U2 data_in<38>
Project.unit<0>.triggerChannel<0><39>=contro U2 data_in<39>
Project.unit<0>.triggerChannel<0><3>=contro U2 data_in<3>
Project.unit<0>.triggerChannel<0><40>=contro U2 data_in<40>
Project.unit<0>.triggerChannel<0><41>=contro U2 data_in<41>
Project.unit<0>.triggerChannel<0><42>=contro U2 data_in<42>
Project.unit<0>.triggerChannel<0><43>=contro U2 data_in<43>
Project.unit<0>.triggerChannel<0><44>=contro U2 data_in<44>
Project.unit<0>.triggerChannel<0><45>=contro U2 data_in<45>
Project.unit<0>.triggerChannel<0><46>=contro U2 data_in<46>
Project.unit<0>.triggerChannel<0><47>=contro U2 data_in<47>
Project.unit<0>.triggerChannel<0><48>=contro U2 data_in<48>
Project.unit<0>.triggerChannel<0><49>=contro U2 data_in<49>
Project.unit<0>.triggerChannel<0><4>=contro U2 data_in<4>
Project.unit<0>.triggerChannel<0><50>=contro U2 data_in<50>
Project.unit<0>.triggerChannel<0><51>=contro U2 data_in<51>
Project.unit<0>.triggerChannel<0><52>=contro U2 data_in<52>
Project.unit<0>.triggerChannel<0><53>=contro U2 data_in<53>
Project.unit<0>.triggerChannel<0><54>=contro U2 data_in<54>
Project.unit<0>.triggerChannel<0><55>=contro U2 data_in<55>
Project.unit<0>.triggerChannel<0><56>=contro U2 data_in<56>
Project.unit<0>.triggerChannel<0><57>=contro U2 data_in<57>
Project.unit<0>.triggerChannel<0><58>=contro U2 data_in<58>
Project.unit<0>.triggerChannel<0><59>=contro U2 data_in<59>
Project.unit<0>.triggerChannel<0><5>=contro U2 data_in<5>
Project.unit<0>.triggerChannel<0><60>=contro U2 data_in<60>
Project.unit<0>.triggerChannel<0><61>=contro U2 data_in<61>
Project.unit<0>.triggerChannel<0><62>=contro U2 data_in<62>
Project.unit<0>.triggerChannel<0><63>=contro U2 data_in<63>
Project.unit<0>.triggerChannel<0><6>=contro U2 data_in<6>
Project.unit<0>.triggerChannel<0><7>=contro U2 data_in<7>
Project.unit<0>.triggerChannel<0><8>=contro U2 data_in<8>
Project.unit<0>.triggerChannel<0><9>=contro U2 data_in<9>
Project.unit<0>.triggerChannel<1><0>=contro U2 data_in_reg<0>
Project.unit<0>.triggerChannel<1><10>=contro U2 data_in_reg<10>
Project.unit<0>.triggerChannel<1><11>=contro U2 data_in_reg<11>
Project.unit<0>.triggerChannel<1><12>=contro U2 data_in_reg<12>
Project.unit<0>.triggerChannel<1><13>=contro U2 data_in_reg<13>
Project.unit<0>.triggerChannel<1><14>=contro U2 data_in_reg<14>
Project.unit<0>.triggerChannel<1><15>=contro U2 data_in_reg<15>
Project.unit<0>.triggerChannel<1><16>=contro U2 data_in_reg<16>
Project.unit<0>.triggerChannel<1><17>=contro U2 data_in_reg<17>
Project.unit<0>.triggerChannel<1><18>=contro U2 data_in_reg<18>
Project.unit<0>.triggerChannel<1><19>=contro U2 data_in_reg<19>
Project.unit<0>.triggerChannel<1><1>=contro U2 data_in_reg<1>
Project.unit<0>.triggerChannel<1><20>=contro U2 data_in_reg<20>
Project.unit<0>.triggerChannel<1><21>=contro U2 data_in_reg<21>
Project.unit<0>.triggerChannel<1><22>=contro U2 data_in_reg<22>
Project.unit<0>.triggerChannel<1><23>=contro U2 data_in_reg<23>
Project.unit<0>.triggerChannel<1><24>=contro U2 data_in_reg<24>
Project.unit<0>.triggerChannel<1><25>=contro U2 data_in_reg<25>
Project.unit<0>.triggerChannel<1><26>=contro U2 data_in_reg<26>
Project.unit<0>.triggerChannel<1><27>=contro U2 data_in_reg<27>
Project.unit<0>.triggerChannel<1><28>=contro U2 data_in_reg<28>
Project.unit<0>.triggerChannel<1><29>=contro U2 data_in_reg<29>
Project.unit<0>.triggerChannel<1><2>=contro U2 data_in_reg<2>
Project.unit<0>.triggerChannel<1><30>=contro U2 data_in_reg<30>
Project.unit<0>.triggerChannel<1><31>=contro U2 data_in_reg<31>
Project.unit<0>.triggerChannel<1><32>=contro U2 data_in_reg<32>
Project.unit<0>.triggerChannel<1><33>=contro U2 data_in_reg<33>
Project.unit<0>.triggerChannel<1><34>=contro U2 data_in_reg<34>
Project.unit<0>.triggerChannel<1><35>=contro U2 data_in_reg<35>
Project.unit<0>.triggerChannel<1><36>=contro U2 data_in_reg<36>
Project.unit<0>.triggerChannel<1><37>=contro U2 data_in_reg<37>
Project.unit<0>.triggerChannel<1><38>=contro U2 data_in_reg<38>
Project.unit<0>.triggerChannel<1><39>=contro U2 data_in_reg<39>
Project.unit<0>.triggerChannel<1><3>=contro U2 data_in_reg<3>
Project.unit<0>.triggerChannel<1><40>=contro U2 data_in_reg<40>
Project.unit<0>.triggerChannel<1><41>=contro U2 data_in_reg<41>
Project.unit<0>.triggerChannel<1><42>=contro U2 data_in_reg<42>
Project.unit<0>.triggerChannel<1><43>=contro U2 data_in_reg<43>
Project.unit<0>.triggerChannel<1><44>=contro U2 data_in_reg<44>
Project.unit<0>.triggerChannel<1><45>=contro U2 data_in_reg<45>
Project.unit<0>.triggerChannel<1><46>=contro U2 data_in_reg<46>
Project.unit<0>.triggerChannel<1><47>=contro U2 data_in_reg<47>
Project.unit<0>.triggerChannel<1><48>=contro U2 data_in_reg<48>
Project.unit<0>.triggerChannel<1><49>=contro U2 data_in_reg<49>
Project.unit<0>.triggerChannel<1><4>=contro U2 data_in_reg<4>
Project.unit<0>.triggerChannel<1><50>=contro U2 data_in_reg<50>
Project.unit<0>.triggerChannel<1><51>=contro U2 data_in_reg<51>
Project.unit<0>.triggerChannel<1><52>=contro U2 data_in_reg<52>
Project.unit<0>.triggerChannel<1><53>=contro U2 data_in_reg<53>
Project.unit<0>.triggerChannel<1><54>=contro U2 data_in_reg<54>
Project.unit<0>.triggerChannel<1><55>=contro U2 data_in_reg<55>
Project.unit<0>.triggerChannel<1><56>=contro U2 data_in_reg<56>
Project.unit<0>.triggerChannel<1><57>=contro U2 data_in_reg<57>
Project.unit<0>.triggerChannel<1><58>=contro U2 data_in_reg<58>
Project.unit<0>.triggerChannel<1><59>=contro U2 data_in_reg<59>
Project.unit<0>.triggerChannel<1><5>=contro U2 data_in_reg<5>
Project.unit<0>.triggerChannel<1><60>=contro U2 data_in_reg<60>
Project.unit<0>.triggerChannel<1><61>=contro U2 data_in_reg<61>
Project.unit<0>.triggerChannel<1><62>=contro U2 data_in_reg<62>
Project.unit<0>.triggerChannel<1><63>=contro U2 data_in_reg<63>
Project.unit<0>.triggerChannel<1><6>=contro U2 data_in_reg<6>
Project.unit<0>.triggerChannel<1><7>=contro U2 data_in_reg<7>
Project.unit<0>.triggerChannel<1><8>=contro U2 data_in_reg<8>
Project.unit<0>.triggerChannel<1><9>=contro U2 data_in_reg<9>
Project.unit<0>.triggerChannel<2><0>=contro U2 tx_data_length<0>
Project.unit<0>.triggerChannel<2><10>=contro U2 tx_data_length<10>
Project.unit<0>.triggerChannel<2><11>=contro U2 tx_data_length<11>
Project.unit<0>.triggerChannel<2><12>=contro U2 tx_data_length<12>
Project.unit<0>.triggerChannel<2><13>=contro U2 tx_data_length<13>
Project.unit<0>.triggerChannel<2><14>=contro U2 tx_data_length<14>
Project.unit<0>.triggerChannel<2><15>=contro U2 tx_data_length<15>
Project.unit<0>.triggerChannel<2><1>=contro U2 tx_data_length<1>
Project.unit<0>.triggerChannel<2><2>=contro U2 tx_data_length<2>
Project.unit<0>.triggerChannel<2><3>=contro U2 tx_data_length<3>
Project.unit<0>.triggerChannel<2><4>=contro U2 tx_data_length<4>
Project.unit<0>.triggerChannel<2><5>=contro U2 tx_data_length<5>
Project.unit<0>.triggerChannel<2><6>=contro U2 tx_data_length<6>
Project.unit<0>.triggerChannel<2><7>=contro U2 tx_data_length<7>
Project.unit<0>.triggerChannel<2><8>=contro U2 tx_data_length<8>
Project.unit<0>.triggerChannel<2><9>=contro U2 tx_data_length<9>
Project.unit<0>.triggerChannel<3><0>=contro U2 e_rd_en_o
Project.unit<0>.triggerChannel<3><1>=contro U2 e_rd_en_reg
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerPortCount=4
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortWidth<0>=64
Project.unit<0>.triggerPortWidth<1>=64
Project.unit<0>.triggerPortWidth<2>=16
Project.unit<0>.triggerPortWidth<3>=2
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
