#ChipScope Core Inserter Project File Version 3.0
#Sat Nov 19 14:33:48 CST 2016
Project.device.designInputFile=F\:\\theproject\\14_ethernet_test\\ethernet_test_cs.ngc
Project.device.designOutputFile=F\:\\theproject\\14_ethernet_test\\ethernet_test_cs.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=F\:\\theproject\\14_ethernet_test\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=
Project.filter<10>=*e_rd_en*
Project.filter<11>=*etx_fifo_rst*
Project.filter<12>=*tx_total_length<*
Project.filter<13>=*tx_data_length<*
Project.filter<14>=*tx_data_length*
Project.filter<15>=*etx_din<*
Project.filter<16>=*etx_din
Project.filter<17>=*etx_din*
Project.filter<18>=*etx_enable*
Project.filter<1>=*ddr3_wren*
Project.filter<2>=*ddr3_data<*
Project.filter<3>=*ddr3_data*
Project.filter<4>=*etx_empty*
Project.filter<5>=*commmand_data<*
Project.filter<6>=*commmand_data*
Project.filter<7>=*command*
Project.filter<8>=*enable*
Project.filter<9>=*camer_rden*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=contro camer_rdclk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=contro ewr_en
Project.unit<0>.dataChannel<100>=contro commmand_data<119>
Project.unit<0>.dataChannel<101>=contro commmand_data<118>
Project.unit<0>.dataChannel<102>=contro commmand_data<117>
Project.unit<0>.dataChannel<103>=contro commmand_data<116>
Project.unit<0>.dataChannel<104>=contro commmand_data<115>
Project.unit<0>.dataChannel<105>=contro commmand_data<114>
Project.unit<0>.dataChannel<106>=contro commmand_data<113>
Project.unit<0>.dataChannel<107>=contro commmand_data<112>
Project.unit<0>.dataChannel<108>=contro etx_empty
Project.unit<0>.dataChannel<109>=contro ddr3_data<0>
Project.unit<0>.dataChannel<10>=contro etx_din<8>
Project.unit<0>.dataChannel<110>=contro ddr3_data<1>
Project.unit<0>.dataChannel<111>=contro ddr3_data<2>
Project.unit<0>.dataChannel<112>=contro ddr3_data<3>
Project.unit<0>.dataChannel<113>=contro ddr3_data<4>
Project.unit<0>.dataChannel<114>=contro ddr3_data<5>
Project.unit<0>.dataChannel<115>=contro ddr3_data<6>
Project.unit<0>.dataChannel<116>=contro ddr3_data<7>
Project.unit<0>.dataChannel<117>=contro ddr3_data<8>
Project.unit<0>.dataChannel<118>=contro ddr3_data<9>
Project.unit<0>.dataChannel<119>=contro ddr3_data<10>
Project.unit<0>.dataChannel<11>=contro etx_din<9>
Project.unit<0>.dataChannel<120>=contro ddr3_data<11>
Project.unit<0>.dataChannel<121>=contro ddr3_data<12>
Project.unit<0>.dataChannel<122>=contro ddr3_data<13>
Project.unit<0>.dataChannel<123>=contro ddr3_data<14>
Project.unit<0>.dataChannel<124>=contro ddr3_data<15>
Project.unit<0>.dataChannel<125>=contro ddr3_data<16>
Project.unit<0>.dataChannel<126>=contro ddr3_data<17>
Project.unit<0>.dataChannel<127>=contro ddr3_data<18>
Project.unit<0>.dataChannel<128>=contro ddr3_data<19>
Project.unit<0>.dataChannel<129>=contro ddr3_data<20>
Project.unit<0>.dataChannel<12>=contro etx_din<10>
Project.unit<0>.dataChannel<130>=contro ddr3_data<21>
Project.unit<0>.dataChannel<131>=contro ddr3_data<22>
Project.unit<0>.dataChannel<132>=contro ddr3_data<23>
Project.unit<0>.dataChannel<133>=contro ddr3_data<24>
Project.unit<0>.dataChannel<134>=contro ddr3_data<25>
Project.unit<0>.dataChannel<135>=contro ddr3_data<26>
Project.unit<0>.dataChannel<136>=contro ddr3_data<27>
Project.unit<0>.dataChannel<137>=contro ddr3_data<28>
Project.unit<0>.dataChannel<138>=contro ddr3_data<29>
Project.unit<0>.dataChannel<139>=contro ddr3_data<30>
Project.unit<0>.dataChannel<13>=contro etx_din<11>
Project.unit<0>.dataChannel<140>=contro ddr3_data<31>
Project.unit<0>.dataChannel<141>=contro ddr3_data<32>
Project.unit<0>.dataChannel<142>=contro ddr3_data<33>
Project.unit<0>.dataChannel<143>=contro ddr3_data<34>
Project.unit<0>.dataChannel<144>=contro ddr3_data<35>
Project.unit<0>.dataChannel<145>=contro ddr3_data<36>
Project.unit<0>.dataChannel<146>=contro ddr3_data<37>
Project.unit<0>.dataChannel<147>=contro ddr3_data<38>
Project.unit<0>.dataChannel<148>=contro ddr3_data<39>
Project.unit<0>.dataChannel<149>=contro ddr3_data<40>
Project.unit<0>.dataChannel<14>=contro etx_din<12>
Project.unit<0>.dataChannel<150>=contro ddr3_data<41>
Project.unit<0>.dataChannel<151>=contro ddr3_data<42>
Project.unit<0>.dataChannel<152>=contro ddr3_data<43>
Project.unit<0>.dataChannel<153>=contro ddr3_data<44>
Project.unit<0>.dataChannel<154>=contro ddr3_data<45>
Project.unit<0>.dataChannel<155>=contro ddr3_data<46>
Project.unit<0>.dataChannel<156>=contro ddr3_data<47>
Project.unit<0>.dataChannel<157>=contro ddr3_data<48>
Project.unit<0>.dataChannel<158>=contro ddr3_data<49>
Project.unit<0>.dataChannel<159>=contro ddr3_data<50>
Project.unit<0>.dataChannel<15>=contro etx_din<13>
Project.unit<0>.dataChannel<160>=contro ddr3_data<51>
Project.unit<0>.dataChannel<161>=contro ddr3_data<52>
Project.unit<0>.dataChannel<162>=contro ddr3_data<53>
Project.unit<0>.dataChannel<163>=contro ddr3_data<54>
Project.unit<0>.dataChannel<164>=contro ddr3_data<55>
Project.unit<0>.dataChannel<165>=contro ddr3_data<56>
Project.unit<0>.dataChannel<166>=contro ddr3_data<57>
Project.unit<0>.dataChannel<167>=contro ddr3_data<58>
Project.unit<0>.dataChannel<168>=contro ddr3_data<59>
Project.unit<0>.dataChannel<169>=contro ddr3_data<60>
Project.unit<0>.dataChannel<16>=contro etx_din<14>
Project.unit<0>.dataChannel<170>=contro ddr3_data<61>
Project.unit<0>.dataChannel<171>=contro ddr3_data<62>
Project.unit<0>.dataChannel<172>=contro ddr3_data<63>
Project.unit<0>.dataChannel<173>=contro ddr3_wren
Project.unit<0>.dataChannel<17>=contro etx_din<15>
Project.unit<0>.dataChannel<18>=contro etx_din<16>
Project.unit<0>.dataChannel<19>=contro etx_din<17>
Project.unit<0>.dataChannel<1>=contro etx_enable
Project.unit<0>.dataChannel<20>=contro etx_din<18>
Project.unit<0>.dataChannel<21>=contro etx_din<19>
Project.unit<0>.dataChannel<22>=contro etx_din<20>
Project.unit<0>.dataChannel<23>=contro etx_din<21>
Project.unit<0>.dataChannel<24>=contro etx_din<22>
Project.unit<0>.dataChannel<25>=contro etx_din<23>
Project.unit<0>.dataChannel<26>=contro etx_din<24>
Project.unit<0>.dataChannel<27>=contro etx_din<25>
Project.unit<0>.dataChannel<28>=contro etx_din<26>
Project.unit<0>.dataChannel<29>=contro etx_din<27>
Project.unit<0>.dataChannel<2>=contro etx_din<0>
Project.unit<0>.dataChannel<30>=contro etx_din<28>
Project.unit<0>.dataChannel<31>=contro etx_din<29>
Project.unit<0>.dataChannel<32>=contro etx_din<30>
Project.unit<0>.dataChannel<33>=contro etx_din<31>
Project.unit<0>.dataChannel<34>=contro etx_din<32>
Project.unit<0>.dataChannel<35>=contro etx_din<33>
Project.unit<0>.dataChannel<36>=contro etx_din<34>
Project.unit<0>.dataChannel<37>=contro etx_din<35>
Project.unit<0>.dataChannel<38>=contro etx_din<36>
Project.unit<0>.dataChannel<39>=contro etx_din<37>
Project.unit<0>.dataChannel<3>=contro etx_din<1>
Project.unit<0>.dataChannel<40>=contro etx_din<38>
Project.unit<0>.dataChannel<41>=contro etx_din<39>
Project.unit<0>.dataChannel<42>=contro etx_din<40>
Project.unit<0>.dataChannel<43>=contro etx_din<41>
Project.unit<0>.dataChannel<44>=contro etx_din<42>
Project.unit<0>.dataChannel<45>=contro etx_din<43>
Project.unit<0>.dataChannel<46>=contro etx_din<44>
Project.unit<0>.dataChannel<47>=contro etx_din<45>
Project.unit<0>.dataChannel<48>=contro etx_din<46>
Project.unit<0>.dataChannel<49>=contro etx_din<47>
Project.unit<0>.dataChannel<4>=contro etx_din<2>
Project.unit<0>.dataChannel<50>=contro etx_din<48>
Project.unit<0>.dataChannel<51>=contro etx_din<49>
Project.unit<0>.dataChannel<52>=contro etx_din<50>
Project.unit<0>.dataChannel<53>=contro etx_din<51>
Project.unit<0>.dataChannel<54>=contro etx_din<52>
Project.unit<0>.dataChannel<55>=contro etx_din<53>
Project.unit<0>.dataChannel<56>=contro etx_din<54>
Project.unit<0>.dataChannel<57>=contro etx_din<55>
Project.unit<0>.dataChannel<58>=contro etx_din<56>
Project.unit<0>.dataChannel<59>=contro etx_din<57>
Project.unit<0>.dataChannel<5>=contro etx_din<3>
Project.unit<0>.dataChannel<60>=contro etx_din<58>
Project.unit<0>.dataChannel<61>=contro etx_din<59>
Project.unit<0>.dataChannel<62>=contro etx_din<60>
Project.unit<0>.dataChannel<63>=contro etx_din<61>
Project.unit<0>.dataChannel<64>=contro etx_din<62>
Project.unit<0>.dataChannel<65>=contro etx_din<63>
Project.unit<0>.dataChannel<66>=contro tx_data_length<0>
Project.unit<0>.dataChannel<67>=contro tx_data_length<1>
Project.unit<0>.dataChannel<68>=contro tx_data_length<2>
Project.unit<0>.dataChannel<69>=contro tx_data_length<3>
Project.unit<0>.dataChannel<6>=contro etx_din<4>
Project.unit<0>.dataChannel<70>=contro tx_data_length<4>
Project.unit<0>.dataChannel<71>=contro tx_data_length<5>
Project.unit<0>.dataChannel<72>=contro tx_data_length<6>
Project.unit<0>.dataChannel<73>=contro tx_data_length<7>
Project.unit<0>.dataChannel<74>=contro tx_data_length<8>
Project.unit<0>.dataChannel<75>=contro tx_data_length<9>
Project.unit<0>.dataChannel<76>=contro tx_data_length<10>
Project.unit<0>.dataChannel<77>=contro tx_data_length<11>
Project.unit<0>.dataChannel<78>=contro tx_data_length<12>
Project.unit<0>.dataChannel<79>=contro tx_data_length<13>
Project.unit<0>.dataChannel<7>=contro etx_din<5>
Project.unit<0>.dataChannel<80>=contro tx_data_length<14>
Project.unit<0>.dataChannel<81>=contro tx_data_length<15>
Project.unit<0>.dataChannel<82>=contro tx_total_length<0>
Project.unit<0>.dataChannel<83>=contro tx_total_length<1>
Project.unit<0>.dataChannel<84>=contro tx_total_length<2>
Project.unit<0>.dataChannel<85>=contro tx_total_length<3>
Project.unit<0>.dataChannel<86>=contro tx_total_length<4>
Project.unit<0>.dataChannel<87>=contro tx_total_length<5>
Project.unit<0>.dataChannel<88>=contro tx_total_length<6>
Project.unit<0>.dataChannel<89>=contro tx_total_length<7>
Project.unit<0>.dataChannel<8>=contro etx_din<6>
Project.unit<0>.dataChannel<90>=contro tx_total_length<8>
Project.unit<0>.dataChannel<91>=contro tx_total_length<9>
Project.unit<0>.dataChannel<92>=contro tx_total_length<10>
Project.unit<0>.dataChannel<93>=contro tx_total_length<11>
Project.unit<0>.dataChannel<94>=contro tx_total_length<12>
Project.unit<0>.dataChannel<95>=contro tx_total_length<13>
Project.unit<0>.dataChannel<96>=contro tx_total_length<14>
Project.unit<0>.dataChannel<97>=contro tx_total_length<15>
Project.unit<0>.dataChannel<98>=contro etx_fifo_rst
Project.unit<0>.dataChannel<99>=contro e_rd_en_o
Project.unit<0>.dataChannel<9>=contro etx_din<7>
Project.unit<0>.dataDepth=2048
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=262
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=contro ewr_en
Project.unit<0>.triggerChannel<10><0>=contro ddr3_wren
Project.unit<0>.triggerChannel<1><0>=contro etx_enable
Project.unit<0>.triggerChannel<2><0>=contro etx_din<0>
Project.unit<0>.triggerChannel<2><10>=contro etx_din<10>
Project.unit<0>.triggerChannel<2><11>=contro etx_din<11>
Project.unit<0>.triggerChannel<2><12>=contro etx_din<12>
Project.unit<0>.triggerChannel<2><13>=contro etx_din<13>
Project.unit<0>.triggerChannel<2><14>=contro etx_din<14>
Project.unit<0>.triggerChannel<2><15>=contro etx_din<15>
Project.unit<0>.triggerChannel<2><16>=contro etx_din<16>
Project.unit<0>.triggerChannel<2><17>=contro etx_din<17>
Project.unit<0>.triggerChannel<2><18>=contro etx_din<18>
Project.unit<0>.triggerChannel<2><19>=contro etx_din<19>
Project.unit<0>.triggerChannel<2><1>=contro etx_din<1>
Project.unit<0>.triggerChannel<2><20>=contro etx_din<20>
Project.unit<0>.triggerChannel<2><21>=contro etx_din<21>
Project.unit<0>.triggerChannel<2><22>=contro etx_din<22>
Project.unit<0>.triggerChannel<2><23>=contro etx_din<23>
Project.unit<0>.triggerChannel<2><24>=contro etx_din<24>
Project.unit<0>.triggerChannel<2><25>=contro etx_din<25>
Project.unit<0>.triggerChannel<2><26>=contro etx_din<26>
Project.unit<0>.triggerChannel<2><27>=contro etx_din<27>
Project.unit<0>.triggerChannel<2><28>=contro etx_din<28>
Project.unit<0>.triggerChannel<2><29>=contro etx_din<29>
Project.unit<0>.triggerChannel<2><2>=contro etx_din<2>
Project.unit<0>.triggerChannel<2><30>=contro etx_din<30>
Project.unit<0>.triggerChannel<2><31>=contro etx_din<31>
Project.unit<0>.triggerChannel<2><32>=contro etx_din<32>
Project.unit<0>.triggerChannel<2><33>=contro etx_din<33>
Project.unit<0>.triggerChannel<2><34>=contro etx_din<34>
Project.unit<0>.triggerChannel<2><35>=contro etx_din<35>
Project.unit<0>.triggerChannel<2><36>=contro etx_din<36>
Project.unit<0>.triggerChannel<2><37>=contro etx_din<37>
Project.unit<0>.triggerChannel<2><38>=contro etx_din<38>
Project.unit<0>.triggerChannel<2><39>=contro etx_din<39>
Project.unit<0>.triggerChannel<2><3>=contro etx_din<3>
Project.unit<0>.triggerChannel<2><40>=contro etx_din<40>
Project.unit<0>.triggerChannel<2><41>=contro etx_din<41>
Project.unit<0>.triggerChannel<2><42>=contro etx_din<42>
Project.unit<0>.triggerChannel<2><43>=contro etx_din<43>
Project.unit<0>.triggerChannel<2><44>=contro etx_din<44>
Project.unit<0>.triggerChannel<2><45>=contro etx_din<45>
Project.unit<0>.triggerChannel<2><46>=contro etx_din<46>
Project.unit<0>.triggerChannel<2><47>=contro etx_din<47>
Project.unit<0>.triggerChannel<2><48>=contro etx_din<48>
Project.unit<0>.triggerChannel<2><49>=contro etx_din<49>
Project.unit<0>.triggerChannel<2><4>=contro etx_din<4>
Project.unit<0>.triggerChannel<2><50>=contro etx_din<50>
Project.unit<0>.triggerChannel<2><51>=contro etx_din<51>
Project.unit<0>.triggerChannel<2><52>=contro etx_din<52>
Project.unit<0>.triggerChannel<2><53>=contro etx_din<53>
Project.unit<0>.triggerChannel<2><54>=contro etx_din<54>
Project.unit<0>.triggerChannel<2><55>=contro etx_din<55>
Project.unit<0>.triggerChannel<2><56>=contro etx_din<56>
Project.unit<0>.triggerChannel<2><57>=contro etx_din<57>
Project.unit<0>.triggerChannel<2><58>=contro etx_din<58>
Project.unit<0>.triggerChannel<2><59>=contro etx_din<59>
Project.unit<0>.triggerChannel<2><5>=contro etx_din<5>
Project.unit<0>.triggerChannel<2><60>=contro etx_din<60>
Project.unit<0>.triggerChannel<2><61>=contro etx_din<61>
Project.unit<0>.triggerChannel<2><62>=contro etx_din<62>
Project.unit<0>.triggerChannel<2><63>=contro etx_din<63>
Project.unit<0>.triggerChannel<2><6>=contro etx_din<6>
Project.unit<0>.triggerChannel<2><7>=contro etx_din<7>
Project.unit<0>.triggerChannel<2><8>=contro etx_din<8>
Project.unit<0>.triggerChannel<2><9>=contro etx_din<9>
Project.unit<0>.triggerChannel<3><0>=contro tx_data_length<0>
Project.unit<0>.triggerChannel<3><10>=contro tx_data_length<10>
Project.unit<0>.triggerChannel<3><11>=contro tx_data_length<11>
Project.unit<0>.triggerChannel<3><12>=contro tx_data_length<12>
Project.unit<0>.triggerChannel<3><13>=contro tx_data_length<13>
Project.unit<0>.triggerChannel<3><14>=contro tx_data_length<14>
Project.unit<0>.triggerChannel<3><15>=contro tx_data_length<15>
Project.unit<0>.triggerChannel<3><1>=contro tx_data_length<1>
Project.unit<0>.triggerChannel<3><2>=contro tx_data_length<2>
Project.unit<0>.triggerChannel<3><3>=contro tx_data_length<3>
Project.unit<0>.triggerChannel<3><4>=contro tx_data_length<4>
Project.unit<0>.triggerChannel<3><5>=contro tx_data_length<5>
Project.unit<0>.triggerChannel<3><6>=contro tx_data_length<6>
Project.unit<0>.triggerChannel<3><7>=contro tx_data_length<7>
Project.unit<0>.triggerChannel<3><8>=contro tx_data_length<8>
Project.unit<0>.triggerChannel<3><9>=contro tx_data_length<9>
Project.unit<0>.triggerChannel<4><0>=contro tx_total_length<0>
Project.unit<0>.triggerChannel<4><10>=contro tx_total_length<10>
Project.unit<0>.triggerChannel<4><11>=contro tx_total_length<11>
Project.unit<0>.triggerChannel<4><12>=contro tx_total_length<12>
Project.unit<0>.triggerChannel<4><13>=contro tx_total_length<13>
Project.unit<0>.triggerChannel<4><14>=contro tx_total_length<14>
Project.unit<0>.triggerChannel<4><15>=contro tx_total_length<15>
Project.unit<0>.triggerChannel<4><1>=contro tx_total_length<1>
Project.unit<0>.triggerChannel<4><2>=contro tx_total_length<2>
Project.unit<0>.triggerChannel<4><3>=contro tx_total_length<3>
Project.unit<0>.triggerChannel<4><4>=contro tx_total_length<4>
Project.unit<0>.triggerChannel<4><5>=contro tx_total_length<5>
Project.unit<0>.triggerChannel<4><6>=contro tx_total_length<6>
Project.unit<0>.triggerChannel<4><7>=contro tx_total_length<7>
Project.unit<0>.triggerChannel<4><8>=contro tx_total_length<8>
Project.unit<0>.triggerChannel<4><9>=contro tx_total_length<9>
Project.unit<0>.triggerChannel<5><0>=contro etx_fifo_rst
Project.unit<0>.triggerChannel<6><0>=contro e_rd_en_o
Project.unit<0>.triggerChannel<7><0>=contro commmand_data<119>
Project.unit<0>.triggerChannel<7><1>=contro commmand_data<118>
Project.unit<0>.triggerChannel<7><2>=contro commmand_data<117>
Project.unit<0>.triggerChannel<7><3>=contro commmand_data<116>
Project.unit<0>.triggerChannel<7><4>=contro commmand_data<115>
Project.unit<0>.triggerChannel<7><5>=contro commmand_data<114>
Project.unit<0>.triggerChannel<7><6>=contro commmand_data<113>
Project.unit<0>.triggerChannel<7><7>=contro commmand_data<112>
Project.unit<0>.triggerChannel<8><0>=contro etx_empty
Project.unit<0>.triggerChannel<9><0>=contro ddr3_data<0>
Project.unit<0>.triggerChannel<9><10>=contro ddr3_data<10>
Project.unit<0>.triggerChannel<9><11>=contro ddr3_data<11>
Project.unit<0>.triggerChannel<9><12>=contro ddr3_data<12>
Project.unit<0>.triggerChannel<9><13>=contro ddr3_data<13>
Project.unit<0>.triggerChannel<9><14>=contro ddr3_data<14>
Project.unit<0>.triggerChannel<9><15>=contro ddr3_data<15>
Project.unit<0>.triggerChannel<9><16>=contro ddr3_data<16>
Project.unit<0>.triggerChannel<9><17>=contro ddr3_data<17>
Project.unit<0>.triggerChannel<9><18>=contro ddr3_data<18>
Project.unit<0>.triggerChannel<9><19>=contro ddr3_data<19>
Project.unit<0>.triggerChannel<9><1>=contro ddr3_data<1>
Project.unit<0>.triggerChannel<9><20>=contro ddr3_data<20>
Project.unit<0>.triggerChannel<9><21>=contro ddr3_data<21>
Project.unit<0>.triggerChannel<9><22>=contro ddr3_data<22>
Project.unit<0>.triggerChannel<9><23>=contro ddr3_data<23>
Project.unit<0>.triggerChannel<9><24>=contro ddr3_data<24>
Project.unit<0>.triggerChannel<9><25>=contro ddr3_data<25>
Project.unit<0>.triggerChannel<9><26>=contro ddr3_data<26>
Project.unit<0>.triggerChannel<9><27>=contro ddr3_data<27>
Project.unit<0>.triggerChannel<9><28>=contro ddr3_data<28>
Project.unit<0>.triggerChannel<9><29>=contro ddr3_data<29>
Project.unit<0>.triggerChannel<9><2>=contro ddr3_data<2>
Project.unit<0>.triggerChannel<9><30>=contro ddr3_data<30>
Project.unit<0>.triggerChannel<9><31>=contro ddr3_data<31>
Project.unit<0>.triggerChannel<9><32>=contro ddr3_data<32>
Project.unit<0>.triggerChannel<9><33>=contro ddr3_data<33>
Project.unit<0>.triggerChannel<9><34>=contro ddr3_data<34>
Project.unit<0>.triggerChannel<9><35>=contro ddr3_data<35>
Project.unit<0>.triggerChannel<9><36>=contro ddr3_data<36>
Project.unit<0>.triggerChannel<9><37>=contro ddr3_data<37>
Project.unit<0>.triggerChannel<9><38>=contro ddr3_data<38>
Project.unit<0>.triggerChannel<9><39>=contro ddr3_data<39>
Project.unit<0>.triggerChannel<9><3>=contro ddr3_data<3>
Project.unit<0>.triggerChannel<9><40>=contro ddr3_data<40>
Project.unit<0>.triggerChannel<9><41>=contro ddr3_data<41>
Project.unit<0>.triggerChannel<9><42>=contro ddr3_data<42>
Project.unit<0>.triggerChannel<9><43>=contro ddr3_data<43>
Project.unit<0>.triggerChannel<9><44>=contro ddr3_data<44>
Project.unit<0>.triggerChannel<9><45>=contro ddr3_data<45>
Project.unit<0>.triggerChannel<9><46>=contro ddr3_data<46>
Project.unit<0>.triggerChannel<9><47>=contro ddr3_data<47>
Project.unit<0>.triggerChannel<9><48>=contro ddr3_data<48>
Project.unit<0>.triggerChannel<9><49>=contro ddr3_data<49>
Project.unit<0>.triggerChannel<9><4>=contro ddr3_data<4>
Project.unit<0>.triggerChannel<9><50>=contro ddr3_data<50>
Project.unit<0>.triggerChannel<9><51>=contro ddr3_data<51>
Project.unit<0>.triggerChannel<9><52>=contro ddr3_data<52>
Project.unit<0>.triggerChannel<9><53>=contro ddr3_data<53>
Project.unit<0>.triggerChannel<9><54>=contro ddr3_data<54>
Project.unit<0>.triggerChannel<9><55>=contro ddr3_data<55>
Project.unit<0>.triggerChannel<9><56>=contro ddr3_data<56>
Project.unit<0>.triggerChannel<9><57>=contro ddr3_data<57>
Project.unit<0>.triggerChannel<9><58>=contro ddr3_data<58>
Project.unit<0>.triggerChannel<9><59>=contro ddr3_data<59>
Project.unit<0>.triggerChannel<9><5>=contro ddr3_data<5>
Project.unit<0>.triggerChannel<9><60>=contro ddr3_data<60>
Project.unit<0>.triggerChannel<9><61>=contro ddr3_data<61>
Project.unit<0>.triggerChannel<9><62>=contro ddr3_data<62>
Project.unit<0>.triggerChannel<9><63>=contro ddr3_data<63>
Project.unit<0>.triggerChannel<9><6>=contro ddr3_data<6>
Project.unit<0>.triggerChannel<9><7>=contro ddr3_data<7>
Project.unit<0>.triggerChannel<9><8>=contro ddr3_data<8>
Project.unit<0>.triggerChannel<9><9>=contro ddr3_data<9>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<10>=1
Project.unit<0>.triggerMatchCount<11>=1
Project.unit<0>.triggerMatchCount<12>=1
Project.unit<0>.triggerMatchCount<13>=1
Project.unit<0>.triggerMatchCount<14>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCount<4>=1
Project.unit<0>.triggerMatchCount<5>=1
Project.unit<0>.triggerMatchCount<6>=1
Project.unit<0>.triggerMatchCount<7>=1
Project.unit<0>.triggerMatchCount<8>=1
Project.unit<0>.triggerMatchCount<9>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<10><0>=0
Project.unit<0>.triggerMatchCountWidth<11><0>=0
Project.unit<0>.triggerMatchCountWidth<12><0>=0
Project.unit<0>.triggerMatchCountWidth<13><0>=0
Project.unit<0>.triggerMatchCountWidth<14><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchCountWidth<4><0>=0
Project.unit<0>.triggerMatchCountWidth<5><0>=0
Project.unit<0>.triggerMatchCountWidth<6><0>=0
Project.unit<0>.triggerMatchCountWidth<7><0>=0
Project.unit<0>.triggerMatchCountWidth<8><0>=0
Project.unit<0>.triggerMatchCountWidth<9><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<10><0>=1
Project.unit<0>.triggerMatchType<11><0>=1
Project.unit<0>.triggerMatchType<12><0>=1
Project.unit<0>.triggerMatchType<13><0>=1
Project.unit<0>.triggerMatchType<14><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerMatchType<4><0>=1
Project.unit<0>.triggerMatchType<5><0>=1
Project.unit<0>.triggerMatchType<6><0>=1
Project.unit<0>.triggerMatchType<7><0>=1
Project.unit<0>.triggerMatchType<8><0>=1
Project.unit<0>.triggerMatchType<9><0>=1
Project.unit<0>.triggerPortCount=11
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<10>=true
Project.unit<0>.triggerPortIsData<11>=true
Project.unit<0>.triggerPortIsData<12>=true
Project.unit<0>.triggerPortIsData<13>=true
Project.unit<0>.triggerPortIsData<14>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortIsData<4>=true
Project.unit<0>.triggerPortIsData<5>=true
Project.unit<0>.triggerPortIsData<6>=true
Project.unit<0>.triggerPortIsData<7>=true
Project.unit<0>.triggerPortIsData<8>=true
Project.unit<0>.triggerPortIsData<9>=true
Project.unit<0>.triggerPortWidth<0>=1
Project.unit<0>.triggerPortWidth<10>=1
Project.unit<0>.triggerPortWidth<11>=64
Project.unit<0>.triggerPortWidth<12>=8
Project.unit<0>.triggerPortWidth<13>=8
Project.unit<0>.triggerPortWidth<14>=8
Project.unit<0>.triggerPortWidth<1>=1
Project.unit<0>.triggerPortWidth<2>=64
Project.unit<0>.triggerPortWidth<3>=16
Project.unit<0>.triggerPortWidth<4>=16
Project.unit<0>.triggerPortWidth<5>=1
Project.unit<0>.triggerPortWidth<6>=1
Project.unit<0>.triggerPortWidth<7>=8
Project.unit<0>.triggerPortWidth<8>=1
Project.unit<0>.triggerPortWidth<9>=64
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
